// Per-route SSR metadata consumed by src/routes/__root.tsx head().
// Generated from page-level Helmet/SEOHead data during the TanStack migration.
export interface RouteMeta { title: string; description: string; }

export const ROUTE_META: Record<string, RouteMeta> = {
  "/": { title: "Eligibly — Détectez. Scorez. Signez. Vos futurs clients en 90 j.", description: "Détectez chaque SASU/SAS/EURL/SARL/SEL immatriculée en France, scorez-la sur votre ICP, contactez-la dans la fenêtre ≤ 90 jours. Digest livré à 7h chaque matin. Pilote 14 j gratuit, sans CB." },
  "/a-propos": { title: "À propos d'Eligibly — Détectez, scorez et signez vos futurs clients", description: "Notre mission : que chaque cabinet EC produise ses propres leads, jamais mutualisés. Équipe, vision, valeurs et engagement de moyens." },
  "/alternatives-primolead-experts-comptables": { title: "Alternatives à PrimoLead pour cabinets d'expertise comptable", description: "Comparatif neutre : PrimoLead, Corporama, Societe.com, Eligibly. Sources, filtres, scoring, canaux d'activation, prix, essai. Choisir le bon outil de génération de leads pour son cabinet EC." },
  "/blog/5-leviers-croissance-cabinet-expertise-comptable": { title: "La croissance d'un cabinet ne se prie pas. Elle se provoque.", description: "5 leviers concrets pour développer un cabinet d'expertise comptable en 2026 : entretenir son réseau prescripteur, se spécialiser, automatiser la production, occuper LinkedIn, jouer le timing de création." },
  "/blog/barometre-acquisition-cabinet-ec-2026": { title: "Baromètre 2026 — L'acquisition client en cabinet d'expertise comptable", description: "Baromètre 2026 de l'acquisition client en cabinet EC : CAC, CPL, mix de canaux, cycle de vente, conversion. Lecture stratégique pour le rôle de conseil de l'expert-comptable." },
  "/blog/barometre-immatriculations-juillet-2026": { title: "Baromètre des nouvelles sociétés commerciales — Édition juillet 2026", description: "Baromètre juillet 2026 : 718 immatriculations analysées, +11,8% vs juin, concentration Tech/Conseil/E-commerce/CHR, capital médian 1 000 €. Signaux structurés pour les cabinets EC." },
  "/blog/cas-client-empartners": { title: "Cas client Empartners : 3 leads qualifiés par semaine, dès 3 mois, sur un site générant quelques centaines de visites", description: "Cas client Empartners.fr : cabinet d'expertise comptable accompagné par Eligibly sur l'image de marque, le site web, le référencement local et la génération de leads. Résultat : 3 leads qualifiés par semaine dès 3 mois, depuis février 2026." },
  "/blog/cout-acquisition-client-cabinet-comptable": { title: "Combien coûte un nouveau client en cabinet d'expertise comptable ? Benchmark 2026", description: "Benchmarks 2026 du coût d'acquisition client en B2B et lecture spécifique pour les cabinets d'expertise comptable : achat de leads, Google Ads, cold email, prospection sortante, apport." },
  "/blog/creations-entreprises-france-2025": { title: "Créations d'entreprises en France : 2025, l'année record qui change la donne pour les cabinets EC", description: "Analyse des données INSEE sur les créations d'entreprises 2024-2025 en France : volume, formes juridiques (SASU, SAS, SARL), régions, et opportunités concrètes pour les cabinets d'expertise comptable." },
  "/blog/creer-site-web-expert-comptable-guide": { title: "Créer le site web d'un cabinet d'expertise comptable : guide de conception 2026", description: "Guide de conception d'un site web pour cabinet d'expertise comptable : positionnement et ICP, arborescence type (accueil, pages missions, verticales, équipe, contact, blog), tunnel de conversion, socle technique et Core Web Vitals, conformité déontologique et RGPD, budget et délais réalistes, indicateurs à suivre." },
  "/blog/fichier-siret-vs-plan-action-comptable": { title: "Fichier de SIRET vs plan d'action : ce qui change vraiment pour un cabinet EC", description: "Comparatif approfondi entre les fichiers de SIRET pour cabinets d'expertise comptable et une plateforme qui livre scoring, canal recommandé et accroche prête à envoyer." },
  "/blog/guide-demarchage-client-expert-comptable": { title: "Kit marketing 2026 pour experts-comptables : sortir de la posture d'attente", description: "Kit marketing 2026 pour experts-comptables : cadre déontologique post-2014, présence sociale, canaux fluides (Slack, WhatsApp), démarchage direct, timing d'immatriculation et checklist marketing en 12 axes (site web qui convertit, Google avis, SEO, visibilité LLM, réseaux sociaux, formulaires de contact, outbound Eligibly, canal prescripteur, lead magnets, webinaires, témoignages et parrainage). Sources CNOEC, INSEE, Légifrance. Cas Empartners : 3 leads / semaine en 3 mois." },
  "/blog/icp-cabinet-expertise-comptable": { title: "Construire l'ICP d'un cabinet d'expertise comptable : la méthode en 5 étapes", description: "Méthode pas-à-pas pour définir l'Ideal Customer Profile d'un cabinet d'expertise comptable : critères durs, signaux, verticales sous-exploitées, exclusions, et conversion en filtres opérationnels." },
  "/blog/lexique-marketing-expert-comptable": { title: "Lexique marketing pour experts-comptables — 30 mots à connaître", description: "Glossaire des 30 termes marketing essentiels pour piloter la prospection en cabinet d'expertise comptable : ICP, scoring, pipeline, touchpoints, CAC, MQL, outbound, séquence, signal d'achat, ROI commercial." },
  "/blog/moderniser-cabinet-etat-lieux-2026": { title: "Moderniser son cabinet : l'état des lieux 2026", description: "État des lieux 2026 de la profession comptable : 20 Md€ de CA, 21 288 cabinets, 77% des entreprises accompagnées, 232 000 futurs clients / an. Les chiffres, tous sourcés." },
  "/blog/moderniser-cabinet-expertise-comptable-ia": { title: "Moderniser un cabinet d'expertise comptable à l'ère de l'IA : les 6 axes qui comptent en 2026", description: "Les 6 axes de modernisation IA d'un cabinet d'expertise comptable en 2026 : production, conseil, relation client, RH, gouvernance et développement commercial. Sources OEC, Cegid, Shine, CREOP." },
  "/blog/observatoire-sasu-sas-juin-2026": { title: "Observatoire des SASU & SAS créées en France — Édition juin 2026", description: "Observatoire mensuel des SASU et SAS immatriculées en France. Lecture stratégique pour les cabinets d'expertise comptable : volumes, verticales, géographie, profils." },
  "/blog/playbook-prospection-cabinet-ec-2026": { title: "Le Playbook 2026 de la prospection en cabinet d'expertise comptable", description: "Playbook complet pour structurer la prospection d'un cabinet d'expertise comptable en 2026 : ICP, organisation, séquences, posture conseil, IA, gouvernance." },
  "/blog/referencement-local-expert-comptable": { title: "Référencement local d'un expert-comptable : la méthode complète 2026", description: "Méthode de référencement local pour cabinet d'expertise comptable : optimisation de la fiche Google Business Profile, collecte d'avis, cohérence NAP, pages locales et verticales, netlinking de proximité, visibilité dans ChatGPT et Perplexity. Plan d'action 90 jours et KPIs." },
  "/cabinet/cas-usage": { title: "Cas d'usage — Eligibly pour cabinets d'expertise comptable", description: "Trois cas d'usage détaillés : cabinet généraliste 8 collaborateurs, cabinet spécialisé restauration, cabinet full-remote startups/e-commerce. Configuration, signaux, plan d'action." },
  "/cabinet/cas-usage/cabinet-8-collaborateurs-departement": { title: "Cabinet 8 collaborateurs : 30 leads/semaine dans son département", description: "Cas d'usage cabinet EC généraliste de 8 collaborateurs : configuration ICP, filtres INPI/BODACC, plan d'action semaine type. 30 prospects qualifiés / semaine sur un département." },
  "/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce": { title: "Cabinet full-remote : cibler startups & e-commerçants — cas d'usage", description: "Cabinet 100 % remote : ciblage national SASU tech + e-commerce, canal LinkedIn + email prioritaire, plan d'action semaine type." },
  "/cabinet/cas-usage/cabinet-specialise-restauration": { title: "Cabinet EC spécialisé restauration : détecter les nouvelles SAS/SARL", description: "Cas d'usage cabinet vertical restauration : filtres NAF 56xx, capital, licence III/IV, plan d'action paie + juridique. Prospection ciblée haut de gamme." },
  "/cabinet/glossaire": { title: "Glossaire — Prospection & génération de leads cabinet d'expertise comptable", description: "Définitions courtes et précises : SIRENE, INPI, BODACC, ICP, scoring prédictif, CAC, LTV, code APE 6920Z, SASU, SAS, EURL, canal d'activation. Glossaire pour cabinets EC." },
  "/canaux-activation": { title: "Canaux d'activation cabinet : WhatsApp Business, LinkedIn, email, appel, courrier", description: "Pour chaque lead cabinet, le meilleur canal : WhatsApp Business, LinkedIn, email, appel, Instagram DM ou courrier en-tête. Timing, méthode, taux de conversion observés." },
  "/cgu": { title: "Conditions générales d'utilisation — Eligibly", description: "Conditions générales d'utilisation d'Eligibly : accès au service, obligations utilisateurs, propriété intellectuelle, responsabilités et résiliation." },
  "/confidentialite": { title: "Politique de confidentialité — Eligibly", description: "Politique de confidentialité et RGPD d'Eligibly : données collectées, finalités, durées de conservation, droits d'accès et de suppression." },
  "/connexion": { title: "Connexion — Eligibly", description: "Connectez-vous à votre espace Eligibly pour accéder à vos leads scorés et votre plan d'action quotidien." },
  "/demo": { title: "Démo Eligibly — 10 leads scorés sur votre zone, en 20 min", description: "Réservez une démo 20 min : 10 SASU/SAS/EURL/SARL/SEL scorées sur votre zone, canal d'approche recommandé, accroche prête à envoyer. Sans CB, sans engagement." },
  "/image-de-marque-expert-comptable": { title: "Image de marque expert-comptable : positionnement et preuves", description: "Construire l'image de marque d'un cabinet d'expertise comptable : positionnement, verticalisation, preuves, identité, discours associés. Cadre opérationnel et limites déontologiques." },
  "/inscription": { title: "Inscription — Eligibly", description: "Créez votre compte Eligibly et démarrez votre pilote de 14 jours gratuit, sans carte bancaire." },
  "/leads-experts-comptables": { title: "Génération de leads pour experts-comptables — Eligibly", description: "Logiciel de génération de leads vertical pour cabinets d'expertise comptable. Détection SASU/SAS/EURL/SARL/SEL immatriculées, scoring expliqué, canaux d'activation. Sources INPI · Sirene · BODACC. Pilote 14 j sans CB." },
  "/marque-et-visibilite-expert-comptable": { title: "Marque & visibilité expert-comptable — l'offre Eligibly (2026)", description: "Offre marque & visibilité pour cabinet d'expertise comptable : actifs digitaux, cas clients documentés, calculateur d'impact visibilité et tableaux de bord de maturité." },
  "/mentions-legales": { title: "Mentions légales — Eligibly", description: "Mentions légales d'Eligibly : éditeur GM2.0 SAS, RCS Paris 930 166 913, siège 9 Avenue de Bouvines 75011 Paris, hébergement et contact." },
  "/newsletter": { title: "Newsletter Eligibly — Le digest prospection des cabinets EC", description: "Recevez chaque mois les chiffres d'immatriculation, benchmarks CAC et méthodes de prospection pour cabinets d'expertise comptable." },
  "/newsletter-config": { title: "Configuration newsletter — Eligibly", description: "Gérez vos préférences d'abonnement à la newsletter Eligibly." },
  "/pourquoi-ce-lead-est-prioritaire": { title: "Fiche lead cabinet EC : score 84/100 expliqué (exemple)", description: "Exemple concret : SASU conseil IT à Paris, capital 5 000 €, score 84/100. Signaux positifs, points à vérifier, canal recommandé, accroche prête à envoyer." },
  "/presence-digitale-cabinet-comptable": { title: "Présence digitale cabinet comptable : socle technique et cadence", description: "Checklist de présence digitale pour cabinet d'expertise comptable : site, fiche Google, LinkedIn, annuaires métier, avis, contenu. Priorités, coûts et cadence réaliste." },
  "/produit": { title: "Détection & prospection — L'offre Eligibly pour cabinets EC", description: "Détection quotidienne des nouvelles SASU/SAS/EURL/SARL/SEL, filtres ICP, scoring expliqué et canal d'approche recommandé (LinkedIn, email, appel, WhatsApp, courrier). Sales Assistant inclus. RGPD." },
  "/prospection-cabinet-comptable": { title: "Prospection cabinet comptable — La méthode 2026 (guide complet)", description: "Structurer une prospection rentable pour cabinet EC en 2026 : sourcing, scoring, séquences multicanal, gouvernance, KPIs. Guide opérationnel + modèles." },
  "/ressources": { title: "Ressources cabinet EC — Baromètres, playbooks & analyses sourcées", description: "Baromètres CAC, playbooks de prospection, ICP, séquences multicanal, observatoires SASU/SAS : les analyses sourcées (INSEE, OEC, Atlas) pour votre cabinet." },
  "/sales-assistant": { title: "Sales Assistant Eligibly — Copilote IA de prospection pour cabinets EC", description: "4 canaux (LinkedIn · Email · Téléphone · Courrier), 9 besoins détectés par lead, plan d'action prêt à envoyer. À partir de 10 € HT/lead, pilote 14 jours sans CB." },
  "/simulateur-roi-ia-cabinet": { title: "Simulateur ROI IA cabinet comptable — Gains chiffrés en 4 étapes", description: "Calculez les gains nets de l'IA pour votre cabinet d'expertise comptable : production, conseil, prospection. Simulateur gratuit en 4 étapes, résultats immédiats." },
  "/solutions": { title: "Cas d'usage cabinet EC — 6 profils, filtres & bénéfices concrets", description: "6 verticales cabinet EC : Tech, Conseil, Santé, Artisans, Grands cabinets, Structuration commerciale. Filtres appliqués et gains chiffrés par profil." },
  "/tarifs": { title: "Tarifs Eligibly — À partir de 10 € le lead qualifié, devis sur mesure", description: "À partir de 10 € le lead qualifié, ajusté à votre volume et à la taille de votre cabinet EC. Pilote 14 jours sans carte bancaire. Résiliation mensuelle." },
  "/unsubscribe": { title: "Désabonnement — Eligibly", description: "Gérez votre désabonnement aux communications Eligibly." },
  "/verticales/btp-artisans": { title: "Verticale BTP & Artisans — Eligibly pour cabinets EC du bâtiment", description: "Détectez chaque nouvelle SASU/SAS/EURL/SARL/SEL BTP (NAF 41-43). Signaux : capital, qualification RGE, sous-traitance. Besoins autoliquidation TVA, garantie décennale, paie." },
  "/verticales/e-commerce": { title: "Verticale E-commerce — Eligibly pour cabinets EC spécialisés DNVB & marketplaces", description: "Ciblez les nouvelles SASU/SAS/EURL/SARL/SEL e-commerce (NAF 47.91B, 47.19B). Signaux : Shopify, WooCommerce, dropshipping. Besoins TVA UE, OSS/IOSS, marketplaces." },
  "/verticales/holdings-groupes": { title: "Verticale Holdings & Groupes — Eligibly pour cabinets EC haut de gamme", description: "Ciblez les nouvelles holdings, SPFPL, sociétés civiles patrimoniales. Signaux : capital élevé, multi-associés, montage LBO. ARPU 8-25 k€/an." },
  "/verticales/professions-liberales-sante": { title: "Verticale Professions libérales & Santé — Eligibly pour cabinets EC BNC/SEL", description: "Ciblez les nouvelles SELAS, SELARL, SASU BNC (médecins, kinés, avocats, architectes). Besoins arbitrage BNC vs SEL, CARPIMKO, retraite libérale." },
  "/verticales/restauration-chr": { title: "Verticale Restauration & CHR — Eligibly pour cabinets spécialisés paie multi-établissements", description: "Détectez chaque nouvelle SAS/SARL restauration (NAF 56xx). Signaux licence III/IV, capital, multi-établissements. Besoins paie, TVA, juridique." },
  "/verticales/sasu-tech": { title: "Verticale SASU Tech & Conseil IT — Eligibly pour cabinets EC", description: "Configuration Eligibly pour cibler les nouvelles SASU tech, freelances IT et micro-ESN. Filtres NAF 62/63, capital, dirigeant ex-ESN. Digest matinal + plan d'action LinkedIn/email." },
  "/visibilite-expert-comptable": { title: "Visibilité expert-comptable : être trouvé, choisi et cité (2026)", description: "Méthode de visibilité pour cabinet d'expertise comptable : fiche Google Business, référencement local, contenu, présence dans les LLM. Indicateurs et arbitrages de budget." },
  "/waitlist/success": { title: "Inscription confirmée — Eligibly", description: "Votre inscription à la liste d'attente Eligibly est confirmée. Nous revenons vers vous rapidement." },
};

export const DEFAULT_META: RouteMeta = ROUTE_META["/"]!;

export const NOT_FOUND_META: RouteMeta = {
  title: "Page introuvable — Eligibly",
  description: "Cette page n'existe pas ou n'est plus disponible.",
};

function normalizePath(pathname: string): string {
  return pathname.length > 1 ? pathname.replace(/\/+$/, "") : pathname;
}

/** Une route est connue uniquement si elle est déclarée dans ROUTE_META. */
export function isKnownRoute(pathname: string): boolean {
  return normalizePath(pathname) in ROUTE_META;
}

export function getRouteMeta(pathname: string): RouteMeta {
  const path = normalizePath(pathname);
  return ROUTE_META[path] ?? NOT_FOUND_META;
}

export function getCanonicalUrl(pathname: string): string {
  const path = pathname.length > 1 ? pathname.replace(/\/+$/, "") : pathname;
  return path === "/" ? "https://eligibly.ai/" : `https://eligibly.ai${path}`;
}
