project_id = "qilmxedcmzjytbrssfbv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false
