import { LandingCabinetLayout } from "@/pages/cabinet/LandingCabinetLayout";

const Glossary = () => (
  <LandingCabinetLayout
    seoTitle="Glossary — prospecting & lead generation for accounting firms | Eligibly"
    seoDescription="Short definitions for accounting-firm prospecting: SIRENE, INPI, BODACC, ICP, predictive scoring, CAC, LTV, NAF code, SASU, SAS, EURL, activation channel."
    canonicalPath="/en/glossary"
    eyebrow="Glossary"
    h1a="Glossary — prospecting &"
    h1b="lead generation"
    h1c="for accounting firms"
    intro="Short, plain-English definitions of the terms used across our product and content."
    bullets={[
      "Data sources: INPI, SIRENE, BODACC, Infogreffe",
      "Marketing metrics: ICP, CAC, LTV, activation channel",
      "Legal forms: SAS, SASU, SARL, EURL, SEL",
    ]}
    ctaPrimary="Request 3 test leads"
    ctaNote="Delivered within 48h — no commitment, no card."
    sections={[
      {
        title: "Data sources",
        body: (
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>INPI</strong> — French national business register (legal data, directors, statutes).</li>
            <li><strong>SIRENE / INSEE</strong> — French company registry (SIRET/SIREN identifiers, industry codes, addresses).</li>
            <li><strong>BODACC</strong> — Official French bulletin of civil and commercial announcements.</li>
            <li><strong>Infogreffe</strong> — Complementary legal publications.</li>
          </ul>
        ),
      },
      {
        title: "Marketing & sales metrics",
        body: (
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>ICP</strong> — Ideal Customer Profile: the description of the accounts most likely to become and stay clients.</li>
            <li><strong>Predictive scoring</strong> — a 0–100 score combining fit and intent signals to rank leads.</li>
            <li><strong>CAC</strong> — Customer Acquisition Cost: everything you spend to sign one client.</li>
            <li><strong>LTV</strong> — Lifetime Value: gross margin generated by a client over their tenure.</li>
            <li><strong>Activation channel</strong> — the channel used to reach out (LinkedIn, email, phone, letter, Instagram DM).</li>
          </ul>
        ),
      },
      {
        title: "French legal forms (Ltd equivalents)",
        body: (
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>SAS / SASU</strong> — flexible joint-stock company (single-member: SASU). Preferred by tech and consulting founders.</li>
            <li><strong>SARL / EURL</strong> — limited liability company (single-member: EURL). Common in trades and retail.</li>
            <li><strong>SEL</strong> — regulated liberal professions vehicle (health, law).</li>
            <li><strong>NAF code (industry code)</strong> — INSEE-issued industry classifier (e.g. 6920Z for accounting activities).</li>
          </ul>
        ),
      },
    ]}
    faq={[
      { q: "Which registers does Eligibly use?", a: "INPI, SIRENE (INSEE) and BODACC as the primary sources, complemented by Infogreffe." },
      { q: "What legal forms do you cover?", a: "SAS, SASU, SARL, EURL and SEL — the French Ltd equivalents relevant to accounting firms." },
    ]}
    related={[
      { label: "Lead generation for accounting firms", href: "/en/accountant-lead-generation" },
      { label: "PrimoLead alternative", href: "/en/primolead-alternative" },
      { label: "Use cases", href: "/en/use-cases" },
    ]}
  />
);

export default Glossary;