import React, { createContext, useContext, useState, useEffect } from 'react';
import { secureStorage } from '@/utils/security';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// French translations (default)
const translations = {
  fr: {
    // Navigation
    'nav.product': 'Produit',
    'nav.solutions': 'Solutions',
    'nav.pricing': 'Tarifs',
    'nav.resources': 'Ressources',
    'nav.about': 'À propos',
    'nav.login': 'Se connecter',
    'nav.demo': 'Demander une démo',
    
    // Hero Section
    'hero.badge': 'Seule plateforme • IA prédictive • Marchés Publics',
    'hero.title': 'La seule IA qui prédit vos chances',
    'hero.title.highlight': 'sur les marchés publics',
    'hero.title.end': 'avant de candidater',
    'hero.subtitle': 'Eligibly.ai est la première plateforme d\'intelligence artificielle prédictive qui analyse vos chances de succès sur chaque marché public. Rejoignez nos premiers utilisateurs.',
    'hero.cta.primary': 'Faites partie des premiers à essayer notre produit',
    'hero.cta.secondary': 'Voir la démonstration',
    'hero.stats.opportunities': '+200 appels d\'offres analysés quotidiennement dans votre secteur',
    'hero.stats.time': '10x plus rapide pour qualifier un marché',
    'hero.stats.precision': "Aide à la décision: placez l'investissement au bon niveau grâce au pourcentage de succès",
    
    // Hero Stats Section
    'hero.stats.markets.value': '+15M€',
    'hero.stats.markets.label': 'marchés remportés',
    'hero.stats.success.value': '47%',
    'hero.stats.success.label': 'taux de succès',
    'hero.stats.time.value': '6h/sem',
    'hero.stats.time.label': 'temps économisé',
    'hero.stats.ai.value': '94%',
    'hero.stats.ai.label': 'précision IA',
    'hero.stats.usedBy': 'Utilisé par les équipes commerciales les plus performantes',
    'hero.trust.rgpd': 'RGPD Compliant',
    'hero.trust.roi': 'ROI moyen x3',
    'hero.trust.teams': 'Équipes jusqu\'à 50 users',
    'hero.noCard': 'Aucune carte bancaire requise • Essai 14 jours • Plus de compétitivité = meilleures affaires publiques',
    'hero.learnMore': 'En savoir plus :',
    'hero.learnMore.link': 'Comment l\'IA transforme les appels d\'offres publics',
    'hero.title.main': 'La seule IA qui prédit vos chances',
    'hero.title.sub': 'sur les marchés publics avant de candidater',
    'hero.description': 'Eligibly est la première IA spécialisée dans les appels d\'offres publics (AO) et les marchés publics, qui prédit vos chances de succès avant de candidater.',
    
    // Charly Section (Meet Charly)
    'charly.meet.title.prefix': 'Rencontrez',
    'charly.meet.title.highlight': 'Charly by Eligibly',
    'charly.meet.title.suffix': ', votre assistant aux marchés publics',
    'charly.meet.subtitle': "Créé par l'équipe Eligibly, Charly est votre assistant IA spécialisé dans les marchés publics. Il analyse en continu les opportunités avec notre expertise et vous recommande les meilleures chances de succès.",
    
    // Coverage Section
    'coverage.badge.sources': 'Sources de données',
    'coverage.badge.realtime': 'Mise à jour en temps réel',
    'coverage.title': 'Couverture',
    'coverage.title.highlight': 'exhaustive',
    'coverage.subtitle': "Couverture nationale (France) et européenne aujourd’hui, mise à jour en temps réel — plan d’expansion mondiale en cours.",
    'coverage.tab.france': 'France',
    'coverage.tab.europe': 'Europe',
    
    // Features
    'features.title': 'Fonctionnalités',
    'features.title.highlight': 'essentielles',
    'features.subtitle': 'Une plateforme complète pour optimiser votre approche des marchés publics et maximiser vos chances de succès.',
    'features.badge': 'Fonctionnalités',
    // Features Heading (HomePage)
    'features.heading.prefix': 'Une plateforme complète pour votre',
    'features.heading.highlight': 'croissance',
    'features.heading.suffix': '',
    // Core features i18n
    'features.core.surveillance.title': 'Surveillance Multi-Sources',
    'features.core.surveillance.desc': 'Surveillance automatisée de plus de 200 sources officielles en France et en Europe',
    'features.core.ai.title': 'Analyse Intelligente',
    'features.core.ai.desc': "Technologie d'intelligence artificielle pour une qualification automatique des marchés",
    'features.core.detection.title': 'Détection Ciblée',
    'features.core.detection.desc': "Identification automatique des appels d'offres correspondant à votre expertise",
    'features.core.alerts.title': 'Alertes Instantanées',
    'features.core.alerts.desc': 'Alertes prédictives avec présélection volontaire pour éviter la surcharge d’informations — notifications sur vos canaux préférés',
    'features.multisource.title': 'IA prédictive exclusive',
    'features.multisource.desc': 'La seule plateforme qui prédit vos chances avant même de candidater et prémâche certains critères clés (prix optimal, engagements environnementaux, etc.) pour maximiser vos chances.',
    'features.ai.title': 'Analyse de compatibilité automatique',
    'features.ai.desc': 'Analyse votre profil vs les critères de chaque marché pour évaluer la compatibilité et prioriser les dossiers à traiter',
    'features.scoring.title': 'Score prédictif de réussite',
    'features.scoring.desc': 'Affiche un pourcentage de succès pour placer le curseur d’investissement commercial exactement où il faut — un véritable outil d’aide à la décision.',
    'features.notifications.title': 'Alertes intelligentes prédictives',
    'features.notifications.desc': 'Alertes avec présélection volontaire pour éviter la surcharge d’informations et vous garder concentré sur vos objectifs de conversion',
    // Additional feature cards
    'features.analytics.title': 'Analytics complets',
    'features.analytics.desc': 'Tableaux de bord détaillés avec métriques de performance, taux de succès et analyse de la concurrence.',
    'features.compliance.title': 'Conformité assurée',
    'features.compliance.desc': "Vérification automatique des critères d'éligibilité et de conformité pour éviter les erreurs coûteuses.",
    // Flow subheading
    'features.flow.title': "Flux d'opportunités",
    'features.flow.subtitle': 'Simplifiez votre veille',
    
    // Features Stats Section
    'features.stats.tenders.value': '+600',
    'features.stats.tenders.label': 'Appels d\'offres/jour',
    'features.stats.tenders.sublabel': 'analysés automatiquement',
    'features.stats.market.value': '80Md€',
    'features.stats.market.label': 'Marché accessible',
    'features.stats.market.sublabel': 'en France chaque année',
    'features.stats.speed.value': '10x',
    'features.stats.speed.label': 'Plus rapide',
    'features.stats.speed.sublabel': 'que la veille manuelle',
    'features.stats.renewals.value': '+50K',
    'features.stats.renewals.label': 'Renouvellements',
    'features.stats.renewals.sublabel': 'de marchés détectés',
    'features.stats.sources': 'Sources surveillées',
    'features.stats.uptime': 'Disponibilité',
    'features.stats.alertDelay': 'Délai moyen d\'alerte',
    
    // Market Stats Section
    'market.title': 'Les chiffres clés des',
    'market.title.highlight': 'marchés publics',
    'market.subtitle': 'Un secteur majeur de l\'économie française avec de nombreuses opportunités pour les entreprises',
    'market.stats.volume': '200 milliards d\'euros',
    'market.stats.volume.desc': 'de dépense publique par an en France',
    'market.stats.tenders': '157 000',
    'market.stats.tenders.desc': 'appels d\'offres publiés chaque année',
    'market.stats.candidates': '2,5',
    'market.stats.candidates.desc': 'entreprises candidates en moyenne par AO',
    'market.benefits.title': 'Des garanties uniques',
    'market.benefits.payment': 'Garantie de paiement',
    'market.benefits.contracts': 'Contrats pluriannuels',
    'market.benefits.growth': 'Croissance stable',
    
    // CTA Section
    'cta.title': 'Décidez plus vite, gagnez plus',
    'cta.subtitle': 'Gagnez en compétitivité et accélérez vos décisions grâce à notre IA prédictive des marchés publics.',
    'cta.primary': 'Accès anticipé',
    'cta.secondary': 'Découvrez votre score de succès en direct',

    // Home (dashboard card)
    'home.aiDetection': "Détection intelligente d'opportunités",
    'home.analysisInProgress': 'Analyse en cours',
    'home.metrics.new': 'Nouvelles opportunités',
    'home.metrics.fromYesterday': '+4 depuis hier',
    'home.metrics.avgScore': 'Score IA moyen',
    'home.metrics.thisMonth': '+2% ce mois',
    'home.metrics.totalValue': 'Valeur totale',
    'home.metrics.thisWeek': 'Cette semaine',
    'home.priorityOpportunities': 'Opportunités prioritaires',
    'home.recommendedByCharly': 'Recommandé par Charly',
    'home.matchPerfect': 'Match parfait',
    'home.renewal': 'Renouvellement',
    'home.charlyRecommendation': 'Recommandation Charly',
    'home.goodCompatibility': 'Bonne compatibilité',
    'home.charlyInAction': 'Charly AI en action',
    'home.lastAnalysis': 'Dernière analyse: il y a 3 min',
    'home.detectedMore': '+12 opportunités détectées',
    
    // Footer
    'footer.company': 'Société',
    'footer.product': 'Produit',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.copyright': '© 2025 Eligibly.ai. Tous droits réservés.',
    'footer.madeIn': 'Fait avec ❤️ en France',
    'footer.poweredByAI': 'Propulsé par l\'IA',
    
    // Accessibility
    'accessibility.skipToContent': 'Aller au contenu principal',
    'accessibility.home': 'Accueil eligibly.ai',
    'accessibility.navigation.main': 'Navigation principale',
    'accessibility.navigation.mobile': 'Navigation mobile',
    'accessibility.menu.open': 'Ouvrir le menu',
    'accessibility.menu.close': 'Fermer le menu',
    'accessibility.login': 'Se connecter à eligibly.ai',
    'accessibility.demo': 'Demander une démo',
    'accessibility.images.logo': 'Logo eligibly.ai',
    'accessibility.images.hero': 'Interface eligibly.ai - Scoring IA des appels d\'offres publics',
    'accessibility.images.dashboard': 'Tableau de bord eligibly.ai',
    'accessibility.images.feature': 'Illustration de la fonctionnalité',
    'accessibility.language.switch': 'Changer la langue vers',
    
    // Not Found Page
    'notfound.title': 'Page introuvable',
    'notfound.description': "Oups ! La page demandée n'existe pas ou a été déplacée.",
    'notfound.backHome': 'Retour à l\'accueil',
    
    // Dashboard
    'dashboard.title': 'Dashboard Eligibly.ai',
    'dashboard.subtitle': 'Suivi en temps réel',
    'dashboard.live': 'Live',
    'dashboard.opportunities.detected': 'Opportunités détectées',
    'dashboard.ai.precision': 'Précision IA',
    'dashboard.recent.opportunities': 'Opportunités récentes',
    'dashboard.score': 'Score',
    'dashboard.lastAnalysis': 'Dernière analyse: il y a 2 min',
    'dashboard.weeklyGrowth': '+6% cette semaine',
    'dashboard.opportunity1.title': 'Système de gestion documentaire',
    'dashboard.opportunity1.client': 'Ministère de l\'Éducation',
    'dashboard.opportunity2.title': 'Infrastructure cloud',
    'dashboard.opportunity2.client': 'Région Île-de-France',
    'dashboard.opportunity3.title': 'Plateforme e-learning',
    'dashboard.opportunity3.client': 'Université de Lyon',
    
    // CGU Page
    'cgu.title': 'Conditions Générales d\'Utilisation',
    'cgu.lastUpdate': 'Dernière mise à jour',
    
    // Product Page
    'product.badge': 'Intelligence Artificielle • Marchés Publics',
    'product.hero.title': 'La plateforme IA la plus avancée pour les marchés publics',
    'product.hero.subtitle': 'Découvrez comment notre intelligence artificielle révolutionne la détection et l\'analyse des appels d\'offres pour maximiser vos chances de succès.',
    'product.features.title': 'Fonctionnalités',
    'product.features.title.highlight': 'clés',
    'product.features.subtitle': 'Une suite complète d\'outils IA pour transformer votre approche des marchés publics',
    'product.benefits.title': 'Résultats',
    'product.benefits.title.highlight': 'mesurables',
    // Product demo (personas)
    'product.demo.badge': 'Démonstration produit',
    'product.demo.title': 'Solutions par profil métier',
    'product.demo.subtitle': 'Découvrez comment Eligibly s\'adapte à votre rôle dans l\'écosystème des marchés publics',
    'product.demo.profileSelected': 'Profil sélectionné',
    'product.demo.benefits': 'Bénéfices clés',
    'product.demo.actions': 'Actions dans Eligibly',
    'product.demo.cta.title': 'Eligibly s\'adapte à votre rôle',
    'product.demo.cta.subtitle': 'Découvrez votre scénario métier personnalisé dans une démonstration adaptée à vos besoins spécifiques.',
    'product.demo.cta.button': 'Planifier une démo personnalisée',
    // Personas
    'product.demo.persona.acheteur.title': 'Responsable des marchés publics / Acheteur public',
    'product.demo.persona.acheteur.desc': 'Vous supervisez les achats et sélectionnez les meilleurs prestataires pour votre collectivité ou administration. Votre défi : identifier rapidement les entreprises les plus pertinentes et sécuriser vos choix.',
    'product.demo.persona.acheteur.b1': 'Comparez automatiquement vos fournisseurs',
    'product.demo.persona.acheteur.b2': 'Analysez et classez les candidatures en un clic',
    'product.demo.persona.acheteur.b3': 'Optimisez vos achats pour plus d’efficacité',
    'product.demo.persona.acheteur.a1': 'Identifiez et qualifiez vos prestataires idéaux',
    'product.demo.persona.acheteur.a2': 'Gérez et suivez facilement vos présélections',
    'product.demo.persona.acheteur.a3': 'Vérifiez automatiquement la conformité technique et administrative',
    
    'product.demo.persona.chef.title': 'Chef de projet / Pilote marché',
    'product.demo.persona.chef.desc': "Vous coordonnez les projets d'achat public et pilotez les consultations. Votre défi : garantir la cohérence entre besoins métier et offres du marché tout en respectant les délais.",
    'product.demo.persona.chef.b1': "Vue d'ensemble consolidée de tous les marchés en cours",
    'product.demo.persona.chef.b2': 'Comparaison objective et automatisée des réponses',
    'product.demo.persona.chef.b3': 'Traçabilité complète des décisions et critères',
    'product.demo.persona.chef.a1': 'Compare et consolide les différentes réponses',
    'product.demo.persona.chef.a2': "Valide l'adéquation offre/besoin métier",
    'product.demo.persona.chef.a3': 'Coordonne les équipes et respecte les échéances',
    
    'product.demo.persona.commercial.title': 'Responsable commercial / Business Developer',
    'product.demo.persona.commercial.desc': 'Vous développez le portefeuille clients de votre PME/ESN dans le secteur public. Votre objectif : détecter les opportunités les plus prometteuses et maximiser vos taux de réussite.',
    'product.demo.persona.commercial.b1': 'Détection automatique des AO compatibles',
    'product.demo.persona.commercial.b2': 'Score de pertinence en temps réel',
    'product.demo.persona.commercial.b3': 'Alertes personnalisées par secteur',
    'product.demo.persona.commercial.a1': 'Filtre et surveille les opportunités par secteur',
    'product.demo.persona.commercial.a2': 'Analyse la concurrence et les critères de sélection',
    'product.demo.persona.commercial.a3': 'Propose une stratégie de réponse personnalisée',
    
    'product.demo.persona.consultant.title': 'Consultant / Cabinet de conseil',
    'product.demo.persona.consultant.desc': 'Vous accompagnez vos clients dans leur stratégie de développement sur les marchés publics. Votre valeur ajoutée : l\'expertise et la veille stratégique pour maximiser leurs succès.',
    'product.demo.persona.consultant.b1': 'Veille sectorielle exhaustive',
    'product.demo.persona.consultant.b2': 'Analyse concurrentielle avancée',
    'product.demo.persona.consultant.b3': 'Rapports automatisés pour clients',
    'product.demo.persona.consultant.a1': 'Effectue une veille marché complète et ciblée',
    'product.demo.persona.consultant.a2': 'Prépare les réponses stratégiques optimisées',
    'product.demo.persona.consultant.a3': 'Télécharge et analyse les DCE pertinents',

    // Solutions Page  
    'solutions.badge': 'Solutions sur mesure',
    'solutions.hero.title': 'Une solution pour chaque',
    'solutions.hero.title.highlight': 'profil métier',
    'solutions.hero.subtitle': 'Notre IA s\'adapte aux besoins spécifiques de votre secteur et de votre rôle pour maximiser votre performance commerciale.',
    'solutions.commercial.title': 'Équipes Commerciales',
    'solutions.commercial.subtitle': 'Vendeurs & Business Developers',
    'solutions.commercial.description': 'Détectez automatiquement les opportunités qui correspondent parfaitement à votre offre et maximisez votre taux de conversion.',
    'solutions.commercial.cta': 'Booster mes ventes',
    'solutions.consultant.title': 'Consultants & AMO',
    'solutions.consultant.subtitle': 'Assistance à Maîtrise d\'Ouvrage',
    'solutions.consultant.description': 'Accompagnez vos clients avec une expertise data-driven et une veille exhaustive des marchés publics de votre secteur.',
    'solutions.consultant.cta': 'Enrichir mon expertise',
    'solutions.public.title': 'Acheteurs Publics',
    'solutions.public.subtitle': 'Collectivités & Administrations',
    'solutions.public.description': 'Optimisez vos achats publics grâce à l\'intelligence de marché et aux benchmarks automatisés de notre IA.',
    'solutions.public.cta': 'Optimiser mes achats',
    'solutions.usecases.title': 'Cas d\'usage',
    'solutions.usecases.title.highlight': 'clients',
    'solutions.usecases.subtitle': 'Découvrez comment nos clients transforment leur performance commerciale',
    
    // Pricing Page
    'pricing.badge': 'Tarifs transparents',
    'pricing.hero.title': 'Choisissez votre',
    'pricing.hero.title.highlight': 'plan parfait',
    'pricing.hero.subtitle': 'Des tarifs simples et transparents. Commencez dès aujourd\'hui, évoluez selon vos besoins. Sans engagement.',
    'pricing.guarantee.title': 'Garantie satisfait ou remboursé 30 jours',
    'pricing.guarantee.subtitle': 'Nous sommes convaincus que notre IA révolutionnera votre veille commerciale. Si vous n\'êtes pas satisfait, nous vous remboursons intégralement.',
    // Plans
    'pricing.plan.starter.name': 'Starter',
    'pricing.plan.starter.price': '49',
    'pricing.plan.starter.period': '/mois',
    'pricing.plan.starter.description': 'Parfait pour les petites entreprises qui débutent',
    'pricing.plan.starter.cta': 'Commencer maintenant',
    'pricing.plan.starter.features.1': "Jusqu'à 50 alertes/mois",
    'pricing.plan.starter.features.2': '3 secteurs de surveillance',
    'pricing.plan.starter.features.3': 'Scoring IA basique',
    'pricing.plan.starter.features.4': 'Support email',
    'pricing.plan.starter.features.5': 'Tableau de bord simple',
    'pricing.plan.starter.features.6': 'Alertes par email',
    
    'pricing.plan.professional.name': 'Professional',
    'pricing.plan.professional.badge': 'Le plus populaire',
    'pricing.plan.professional.price': '149',
    'pricing.plan.professional.period': '/mois',
    'pricing.plan.professional.description': 'Pour les entreprises en croissance',
    'pricing.plan.professional.cta': 'Essayer 14 jours',
    'pricing.plan.professional.features.1': 'Alertes illimitées',
    'pricing.plan.professional.features.2': 'Tous secteurs surveillés',
    'pricing.plan.professional.features.3': 'Scoring IA avancé + analyse concurrence',
    'pricing.plan.professional.features.4': 'Support prioritaire',
    'pricing.plan.professional.features.5': 'Tableau de bord complet',
    'pricing.plan.professional.features.6': 'Alertes Slack/Teams/Email',
    'pricing.plan.professional.features.7': 'Intégrations CRM',
    'pricing.plan.professional.features.8': 'Rapports personnalisés',
    'pricing.plan.professional.features.9': 'API disponible',
    
    'pricing.plan.enterprise.name': 'Enterprise',
    'pricing.plan.enterprise.badge': 'Premium',
    'pricing.plan.enterprise.price': 'Sur mesure',
    'pricing.plan.enterprise.period': '',
    'pricing.plan.enterprise.description': 'Solution personnalisée pour les grandes organisations',
    'pricing.plan.enterprise.cta': 'Nous contacter',
    'pricing.plan.enterprise.features.1': 'Volume personnalisé',
    'pricing.plan.enterprise.features.2': 'Surveillance sur mesure',
    'pricing.plan.enterprise.features.3': 'IA personnalisée + machine learning',
    'pricing.plan.enterprise.features.4': 'Account manager dédié',
    'pricing.plan.enterprise.features.5': 'Tableaux de bord personnalisés',
    'pricing.plan.enterprise.features.6': 'Intégrations complètes',
    'pricing.plan.enterprise.features.7': 'Formation équipe',
    'pricing.plan.enterprise.features.8': 'SLA garanti',
    'pricing.plan.enterprise.features.9': 'Déploiement on-premise possible',
    
    // FAQ
    'pricing.faq.title': 'Questions',
    'pricing.faq.title.highlight': 'fréquentes',
    'pricing.faq.q1.title': 'Puis-je changer de plan à tout moment ?',
    'pricing.faq.q1.desc': 'Oui, vous pouvez upgrader ou downgrader votre plan à tout moment. Les changements prennent effet immédiatement.',
    'pricing.faq.q2.title': 'Y a-t-il des frais de setup ?',
    'pricing.faq.q2.desc': 'Aucun frais de setup. Vous ne payez que votre abonnement mensuel, sans engagement.',
    'pricing.faq.q3.title': "Que se passe-t-il après l'essai ?",
    'pricing.faq.q3.desc': "Vous pouvez continuer avec un plan payant ou revenir à un plan d'entrée limité. Aucune carte bancaire requise pour l'essai.",
    'pricing.faq.q4.title': 'Support technique inclus ?',
    'pricing.faq.q4.desc': 'Oui, tous les plans incluent le support. Le plan Pro+ bénéficie d\'un support prioritaire.',
    
    // Bottom CTA metrics
    'pricing.bottom.trialDays': '14 jours',
    'pricing.bottom.trialLabel': 'Essai',
    'pricing.bottom.setupFee': '0€',
    'pricing.bottom.setupLabel': 'Frais de setup',
    'pricing.bottom.supportHours': '24/7',
    'pricing.bottom.supportLabel': 'Support inclus',
    
    // Resources Page
    'resources.badge': 'Centre de ressources',
    'resources.hero.title': 'Tout pour réussir vos',
    'resources.hero.title.highlight': 'marchés publics',
    'resources.hero.subtitle': 'Guides, tutoriels, analyses et bonnes pratiques pour maximiser votre performance commerciale dans les marchés publics.',
    'resources.featured.title': 'Article à la une',
    'resources.featured.subtitle': 'Notre sélection de la semaine',
    'resources.articles.title': 'Derniers articles',
    'resources.articles.subtitle': 'Conseils et analyses d\'experts',
    'resources.guides.title': 'Guides et',
    'resources.guides.title.highlight': 'templates',
    'resources.guides.subtitle': 'Ressources pratiques à télécharger',
    'resources.videos.title': 'Tutoriels',
    'resources.videos.title.highlight': 'vidéo',
    'resources.videos.subtitle': 'Apprenez à utiliser Eligibly.ai efficacement',
    // Resources Coming soon
    'resources.comingSoon': 'Bientôt disponible',
    'resources.dontMiss': 'Ne manquez pas le',
    'resources.notifyMe': 'Me prévenir',
    'resources.emailPlaceholder': 'Votre adresse email',
    'resources.notifyThanks': 'Merci ! Vous serez notifié dès la sortie.',
    'resources.notifyHelp': "Recevez un email dès qu'une nouvelle ressource est disponible",
    // Resources extra
    'resources.hero.blurb': 'Nous préparons une bibliothèque complète de ressources pour vous aider à exceller dans les marchés publics. Guides, webinaires, templates et analyses exclusives.',
    'resources.upcoming.title': 'Ce qui vous attend',
    'resources.upcoming.subtitle': 'Découvrez les ressources exclusives que nous préparons pour transformer votre approche des marchés publics',
    'resources.stats.preparing': 'En préparation',
    'resources.contact.title': 'Une question spécifique ?',
    'resources.contact.subtitle': 'En attendant nos ressources, notre équipe est là pour vous accompagner',
    'resources.contact.supportEmail': 'Support Email',
    'resources.contact.response': 'Réponse sous 24h',
    'resources.contact.community': 'Communauté',
    'resources.contact.chat': 'Échanges entre pros',
    'resources.contact.join': 'Rejoindre',
    'resources.contact.consulting': 'Consultation',
    'resources.contact.advice': 'Conseil personnalisé',
    'resources.contact.book': 'Prendre RDV',
    
    // About Page
    'about.badge': 'À propos d\'Eligibly.ai',
    'about.hero.title': 'Notre mission :',
    'about.hero.title.highlight': 'démocratiser l\'IA',
    'about.hero.subtitle': 'Nous développons les outils d\'intelligence artificielle les plus avancés pour révolutionner la façon dont les entreprises appréhendent les marchés publics.',
    'about.vision.title': 'Notre',
    'about.vision.title.highlight': 'vision',
    'about.values.title': 'Nos',
    'about.values.title.highlight': 'valeurs',
    'about.values.subtitle': 'Les principes qui guident chacune de nos décisions et innovations',
    'about.team.title': 'Notre',
    'about.team.title.highlight': 'équipe',
    'about.team.subtitle': 'Des experts passionnés par l\'IA et les marchés publics',
    'about.security.title': 'Sécurité et',
    'about.security.title.highlight': 'conformité',
    'about.security.subtitle': 'Vos données sont notre priorité absolue. Nous respectons les plus hauts standards de sécurité.',
    'about.hero.why': 'Pourquoi Charly by Eligibly ?',
    'about.hero.desc': "Charly by Eligibly est bien plus qu'un outil : c'est votre partenaire d'exception, votre bras droit essentiel pour conquérir les marchés publics grâce à l'innovation d'Eligibly.",
    'about.problem.title': 'Le problème',
    
    // Demo Page
    'demo.badge': 'Démonstration personnalisée',
    'demo.hero.title': 'Découvrez votre',
    'demo.hero.title.highlight': 'potentiel IA',
    'demo.hero.subtitle': 'Réservez votre démonstration personnalisée de 30 minutes et découvrez comment notre IA peut transformer votre approche des marchés publics.',
    'demo.form.title': 'Réservez votre démonstration',
    'demo.form.subtitle': 'Complétez ce formulaire et nos experts vous contacteront sous 2h',
    'demo.benefits.title': 'Ce que vous découvrirez',
    'demo.program.title': 'Au programme de votre démo',
    'demo.hero.detail.duration': '30 minutes personnalisées',
    'demo.hero.detail.slots': 'Créneaux disponibles',
    'demo.hero.detail.nocommit': 'Sans engagement',

    // Demo Form Fields (FR)
    'demo.form.firstName': 'Prénom *',
    'demo.form.lastName': 'Nom *',
    'demo.form.email': 'Email professionnel *',
    'demo.form.company': 'Entreprise *',
    'demo.form.role': 'Rôle *',
    'demo.form.role.placeholder': 'Sélectionnez votre rôle',
    'demo.form.role.commercial': 'Commercial / Business developer',
    'demo.form.role.direction': 'Direction / CEO',
    'demo.form.role.marketing': 'Marketing / Communication',
    'demo.form.role.consultant': 'Consultant / AMO',
    'demo.form.role.buyer': 'Acheteur public',
    'demo.form.role.other': 'Autre',
    'demo.form.sector': 'Secteur',
    'demo.form.sector.placeholder': 'Choisissez votre secteur',
    'demo.form.sector.tech': 'Technologie / Digital',
    'demo.form.sector.construction': 'Construction',
    'demo.form.sector.business': 'Services aux entreprises',
    'demo.form.sector.health': 'Santé / Médical',
    'demo.form.sector.energy': 'Énergie / Environnement',
    'demo.form.sector.transport': 'Transport / Logistique',
    'demo.form.sector.other': 'Autre',
    'demo.form.teamSize': "Taille de l’équipe",
    'demo.form.teamSize.placeholder': 'Taille de votre équipe',
    'demo.form.teamSize.1-10': '1–10 personnes',
    'demo.form.teamSize.11-50': '11–50 personnes',
    'demo.form.teamSize.51-200': '51–200 personnes',
    'demo.form.teamSize.200+': '200+ personnes',
    'demo.form.challenges': 'Vos défis actuels (optionnel)',
    'demo.form.challenges.placeholder': 'Décrivez vos principaux défis…',
    'demo.form.newsletter': 'Recevoir des conseils par email (optionnel)',
    'demo.form.submit': 'Réserver ma démo',
    'demo.form.privacy': 'En soumettant ce formulaire, vous acceptez d’être contacté par notre équipe. Vos données sont protégées par notre ',
    'demo.form.privacy.link': 'politique de confidentialité',

    // Demo UI Labels
    'demo.process': 'Processus IA',
    'demo.console': 'Console Charly IA',
    'demo.controls': 'Contrôles',
    'demo.console.waiting': 'Charly IA en attente...',
    'demo.seeMore': 'Voir plus',
    'demo.seeLess': 'Voir moins',
    'demo.close': 'Fermer',
    'demo.launch': 'Lancer IA',
    'demo.analyzing': 'Analyse...',
    'demo.reset': 'Réinitialiser',
    'demo.progress': 'Progression',
    'demo.step': 'Étape',
    'demo.done': 'Terminé ✓',
    'demo.ready': 'Prêt',
    'demo.interface': 'Interface Charly IA',
    'demo.otherResults': 'Autres résultats',
    'demo.otherResultsAO': 'Autres résultats AO',
    'demo.openAO': "Ouvrir l'AO",
    'demo.editFilters': 'Modifier filtres',
    'demo.rerun': 'Relancer',

    // Demo Steps
    'demo.steps.1.title': 'Connexion multi-sources',
    'demo.steps.1.desc': 'Collecte automatique depuis toutes les plateformes officielles',
    'demo.steps.2.title': 'Extraction & Parsing',
    'demo.steps.2.desc': "Analyse et structuration des données d'appels d'offres",
    'demo.steps.3.title': 'Analyse IA Multi-LLM',
    'demo.steps.3.desc': "Intelligence artificielle prédictive pour évaluer la compatibilité",
    'demo.steps.4.title': 'Scoring Algorithmique',
    'demo.steps.4.desc': "Attribution d'un score de chance de réussite personnalisé",

    // AO labels
    'ao.compatibility': 'Compatibilité',
    'ao.budget': 'Budget',
    'ao.deadline': 'Échéance',
    'ao.duration': 'Durée',
    'ao.holder': 'Titulaire',
    
    // AO results section
    'ao.results.title': "Résultats d'Analyse AO",
    'ao.results.found': 'opportunités trouvées',
    'ao.results.avgScore': 'Score moyen',
    'ao.results.excellent': 'excellentes',
    'ao.results.good': 'bonnes',
    'ao.results.filters': 'Filtres',
    'ao.results.search': 'Recherche',
    'ao.results.detailedView': 'Vue détaillée',
    'ao.results.viewAll': 'Voir tous les résultats',
    'ao.results.fullAnalysis': 'Analyse complète',
    'ao.results.totalBudget': 'Budget total disponible',
    'ao.results.avgCompatibility': 'Score moyen de compatibilité',
    'ao.results.publishedCount': 'AO publiés (candidature possible)',
    'ao.status.published': 'publié',
    'ao.status.upcoming': 'à venir',
    'ao.aiCompatibilityScore': 'Score de compatibilité IA',
    'ao.criteria.title': "Critères d'évaluation",
    'ao.criteria.price': 'Prix',
    'ao.criteria.quality': 'Qualité',
    'ao.criteria.performance': 'Performance',
    
    // Login Page
    'login.title': 'Connexion à votre espace',
    'login.subtitle': 'Accédez à votre dashboard Eligibly.ai',
    'login.welcome.title': 'Bienvenue dans votre',
    'login.welcome.title.highlight': 'espace IA',
    'login.welcome.subtitle': 'Accédez à votre tableau de bord personnalisé et découvrez les opportunités détectées par Charly, l\'assistant IA d\'Eligibly.',
    'login.demo.title': 'Découvrez d\'abord notre plateforme',
    'login.demo.subtitle': 'Testez toutes les fonctionnalités pendant 7 jours, sans engagement',
    
    // Common elements
    'common.getStarted': 'Commencer',
    'common.bookDemo': 'Réserver une démo',
    'common.learnMore': 'En savoir plus',
    'common.download': 'Télécharger',
    'common.readMore': 'Lire la suite',
    'common.viewAll': 'Voir tout',
    'common.tryFree': 'Essayer',
    'common.contact': 'Nous contacter',
    'common.login': 'Se connecter',
    'common.signUp': 'S\'inscrire',
    'common.readArticle': 'Lire l\'article',
    'common.watchDemo': 'Voir la démo',
    'common.schedule': 'Planifier',
    'common.subscribe': 'S\'abonner',
    
    // Cookie Consent
    'cookies.title': 'Gestion des cookies',
    'cookies.description': 'Nous utilisons des cookies pour améliorer votre expérience sur notre site. Certains cookies sont nécessaires au fonctionnement du site, d\'autres nous aident à analyser le trafic et à personnaliser le contenu.',
    'cookies.gdpr': 'Conforme au RGPD - Vous pouvez modifier vos préférences à tout moment.',
    'cookies.customize': 'Personnaliser',
    'cookies.necessaryOnly': 'Nécessaires uniquement',
    'cookies.acceptAll': 'Accepter tout',
    'cookies.settings': 'Paramètres de confidentialité',
    'cookies.tabCookies': 'Cookies',
    'cookies.tabPolicy': 'Politique',
    'cookies.necessary.title': 'Cookies nécessaires',
    'cookies.necessary.desc': 'Requis pour le bon fonctionnement du site',
    'cookies.necessary.details': 'Cookies de session, sécurité, préférences de langue, panier d\'achat',
    'cookies.analytics.title': 'Cookies analytiques',
    'cookies.analytics.desc': 'Nous aident à comprendre l\'usage du site',
    'cookies.analytics.details': 'Google Analytics (anonymisé), mesures d\'audience, pages visitées',
    'cookies.marketing.title': 'Cookies marketing',
    'cookies.marketing.desc': 'Pour personnaliser les publicités',
    'cookies.marketing.details': 'Réseaux sociaux, publicités ciblées, remarketing',
    'cookies.preferences.title': 'Cookies de préférences',
    'cookies.preferences.desc': 'Mémorisent vos choix personnels',
    'cookies.preferences.details': 'Thème sombre/clair, région, préférences d\'affichage',
    'cookies.policy.title': 'Notre engagement pour votre vie privée',
    'cookies.policy.intro': 'Eligibly.ai respecte votre vie privée et s\'engage à protéger vos données personnelles conformément au Règlement Général sur la Protection des Données (RGPD).',
    'cookies.policy.purposes': 'Finalités du traitement',
    'cookies.policy.purpose1': 'Fonctionnement technique du site (cookies nécessaires)',
    'cookies.policy.purpose2': 'Analyse de l\'audience et amélioration du service',
    'cookies.policy.purpose3': 'Personnalisation de l\'expérience utilisateur',
    'cookies.policy.purpose4': 'Communication marketing (avec votre consentement)',
    'cookies.policy.rights': 'Vos droits',
    'cookies.policy.rightsText': 'Vous disposez d\'un droit d\'accès, de rectification, d\'effacement, de portabilité et d\'opposition concernant vos données. Contactez-nous à : contact@eligibly.ai',
    'cookies.policy.retention': 'Durée de conservation',
    'cookies.policy.retentionText': 'Les cookies sont conservés pour une durée maximale de 13 mois. Votre consentement est valable 13 mois et peut être retiré à tout moment.',
    'cookies.cancel': 'Annuler',
    'cookies.save': 'Enregistrer les préférences',
  },
  en: {
    // Navigation
    'nav.product': 'Product',
    'nav.solutions': 'Solutions',
    'nav.pricing': 'Pricing',
    'nav.resources': 'Resources',
    'nav.about': 'About',
    'nav.login': 'Sign in',
    'nav.demo': 'Request a demo',
    
    // Hero Section
    'hero.badge': 'Only platform • Predictive AI • Public Procurement',
    'hero.title': 'The only AI that',
    'hero.title.highlight': 'predicts your chances',
    'hero.title.end': 'before you apply',
    'hero.subtitle': 'Eligibly.ai is the first predictive artificial intelligence platform that analyses your chances of success on every public tender. Join our early adopters.',
    'hero.cta.primary': 'Be among the first to try our product',
    'hero.cta.secondary': 'Watch demonstration',
    'hero.stats.opportunities': '+200 public tenders analysed daily in your sector',
    'hero.stats.time': '10x faster to qualify a tender',
    'hero.stats.precision': 'Decision support: invest exactly where it matters with your success percentage',
    
    // Hero Stats Section
    'hero.stats.markets.value': '+15M€',
    'hero.stats.markets.label': 'markets won',
    'hero.stats.success.value': '47%',
    'hero.stats.success.label': 'success rate',
    'hero.stats.time.value': '6h/wk',
    'hero.stats.time.label': 'time saved',
    'hero.stats.ai.value': '94%',
    'hero.stats.ai.label': 'AI precision',
    'hero.stats.usedBy': 'Used by top-performing sales teams',
    'hero.trust.rgpd': 'GDPR Compliant',
    'hero.trust.roi': 'Average ROI x3',
    'hero.trust.teams': 'Teams up to 50 users',
    'hero.noCard': 'No credit card required • 14-day trial • More competitiveness = better public deals',
    'hero.learnMore': 'Learn more:',
    'hero.learnMore.link': 'How AI transforms public tenders',
    'hero.title.main': 'The only AI that predicts your chances',
    'hero.title.sub': 'in public procurement before you apply',
    'hero.description': 'Eligibly is the first AI specialised in public tenders that predicts your chances of success before you apply.',
    
    // Charly Section (Meet Charly)
    'charly.meet.title.prefix': 'Meet',
    'charly.meet.title.highlight': 'Charly by Eligibly',
    'charly.meet.title.suffix': ', your public tender assistant',
    'charly.meet.subtitle': 'Created by the Eligibly team, Charly is your AI assistant specialised in public procurement. It continuously analyses opportunities with our expertise and recommends your best chances of success.',
    
    // Features
    'features.title': 'Essential',
    'features.title.highlight': 'features',
    'features.badge': 'Features',
    'features.subtitle': 'A complete platform to optimise your approach to public procurement and maximise your win rate.',
    // Features Heading (HomePage)
    'features.heading.prefix': 'A complete platform for your',
    'features.heading.highlight': 'growth',
    'features.heading.suffix': '',
    
    // Core features i18n
    'features.core.surveillance.title': 'Multi‑source monitoring',
    'features.core.surveillance.desc': 'Automated monitoring of 200+ official sources in France and Europe',
    'features.core.ai.title': 'Intelligent analysis',
    'features.core.ai.desc': 'Artificial‑intelligence technology for automatic tender qualification',
    'features.core.detection.title': 'Targeted detection',
    'features.core.detection.desc': 'Automatic identification of tenders matching your expertise',
    'features.core.alerts.title': 'Instant alerts',
    'features.core.alerts.desc': 'Predictive opt‑in alerts to avoid information overload — notifications on your preferred channels',
    
    // Features
    'features.multisource.desc': 'The only platform that predicts your chances before you apply and pre‑checks key criteria (optimal pricing, environmental commitments, etc.) to maximise your odds.',
    'features.ai.title': 'Automatic compatibility analysis',
    'features.ai.desc': 'Analyses your profile against each tender’s criteria to assess fit and prioritise the right bids',
    'features.scoring.title': 'Predictive success score',
    'features.scoring.desc': 'Displays a success percentage to set your commercial investment exactly where it matters — a true decision‑support tool',
    'features.notifications.title': 'Predictive smart alerts',
    'features.notifications.desc': 'Opt‑in predictive alerts to avoid information overload and keep you focused on conversions',
    // Additional feature cards
    'features.analytics.title': 'Full analytics',
    'features.analytics.desc': 'Detailed dashboards with performance metrics, win rate and competitive analysis.',
    'features.compliance.title': 'Assured compliance',
    'features.compliance.desc': 'Automatic verification of eligibility and compliance criteria to avoid costly errors.',
    // Flow subheading
    'features.flow.title': 'Opportunity flow',
    'features.flow.subtitle': 'Simplify your monitoring',
    
    // Features Stats Section
    'features.stats.tenders.value': '+600',
    'features.stats.tenders.label': 'Tenders/day',
    'features.stats.tenders.sublabel': 'analysed automatically',
    'features.stats.market.value': '€80B',
    'features.stats.market.label': 'Accessible market',
    'features.stats.market.sublabel': 'in France each year',
    'features.stats.speed.value': '10x',
    'features.stats.speed.label': 'Faster',
    'features.stats.speed.sublabel': 'than manual monitoring',
    'features.stats.renewals.value': '+50K',
    'features.stats.renewals.label': 'Renewals',
    'features.stats.renewals.sublabel': 'detected tenders',
    'features.stats.sources': 'Sources monitored',
    'features.stats.uptime': 'Uptime',
    'features.stats.alertDelay': 'Average alert delay',
    
    'coverage.title': 'Comprehensive',
    'coverage.title.highlight': 'coverage',
    'coverage.subtitle': 'National (France) and European coverage today, updated in real time — global expansion plan underway.',
    'coverage.tab.france': 'France',
    'coverage.tab.europe': 'Europe',
    
    
    // Market Stats Section
    'market.title': 'The',
    'market.title.highlight': 'public opportunity landscape',
    'market.subtitle': 'A major sector of the French economy with numerous opportunities for businesses',
    'market.stats.volume': '200 billion euros',
    'market.stats.volume.desc': 'in public spending per year in France',
    'market.stats.tenders': '157,000',
    'market.stats.tenders.desc': 'tenders published each year',
    'market.stats.candidates': '2.5',
    'market.stats.candidates.desc': 'candidate companies on average per tender',
    'market.benefits.title': 'Unique guarantees',
    'market.benefits.payment': 'Payment guarantee',
    'market.benefits.contracts': 'Multi‑year contracts',
    'market.benefits.growth': 'Stable growth',
    
    // CTA Section
    'cta.title': 'Decide faster, win more',
    'cta.subtitle': 'Gain a competitive edge and make faster decisions with our predictive tender AI.',
    'cta.primary': 'Free early access',
    'cta.secondary': 'See your live success score',

    // Home (dashboard card)
    'home.aiDetection': 'Intelligent opportunity detection',
    'home.analysisInProgress': 'Analysis in progress',
    'home.metrics.new': 'New opportunities',
    'home.metrics.fromYesterday': '+4 since yesterday',
    'home.metrics.avgScore': 'Average AI score',
    'home.metrics.thisMonth': '+2% this month',
    'home.metrics.totalValue': 'Total value',
    'home.metrics.thisWeek': 'This week',
    'home.priorityOpportunities': 'Priority opportunities',
    'home.recommendedByCharly': 'Recommended by Charly',
    'home.matchPerfect': 'Perfect match',
    'home.renewal': 'Renewal',
    'home.charlyRecommendation': 'Charly recommendation',
    'home.goodCompatibility': 'Good compatibility',
    'home.charlyInAction': 'Charly AI in action',
    'home.lastAnalysis': 'Last analysis: 3 min ago',
    'home.detectedMore': '+12 opportunities detected',
    
    // Footer
    'footer.company': 'Company',
    'footer.product': 'Product',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.copyright': '© 2025 Eligibly.ai. All rights reserved.',
    'footer.madeIn': 'Made with ❤️ in France',
    'footer.poweredByAI': 'Powered by AI',
    
    // Accessibility
    'accessibility.skipToContent': 'Skip to main content',
    'accessibility.home': 'eligibly.ai Home',
    'accessibility.navigation.main': 'Main navigation',
    'accessibility.navigation.mobile': 'Mobile navigation',
    'accessibility.menu.open': 'Open menu',
    'accessibility.menu.close': 'Close menu',
    'accessibility.login': 'Login to eligibly.ai',
    'accessibility.demo': 'Request a demo',
    'accessibility.images.logo': 'eligibly.ai Logo',
    'accessibility.images.hero': 'eligibly.ai Interface - AI Scoring for Public Tenders',
    'accessibility.images.dashboard': 'eligibly.ai Dashboard',
    'accessibility.images.feature': 'Feature illustration',
    'accessibility.language.switch': 'Switch language to',
    
    // Not Found Page
    'notfound.title': 'Page not found',
    'notfound.description': 'Oops! The page you are looking for does not exist or has been moved.',
    'notfound.backHome': 'Back to home',
    
    // Dashboard
    'dashboard.title': 'Eligibly.ai dashboard',
    'dashboard.subtitle': 'Real‑time monitoring',
    'dashboard.live': 'Live',
    'dashboard.opportunities.detected': 'Opportunities detected',
    'dashboard.ai.precision': 'AI precision',
    'dashboard.recent.opportunities': 'Recent opportunities',
    'dashboard.score': 'Score',
    'dashboard.lastAnalysis': 'Last analysis: 2 min ago',
    'dashboard.weeklyGrowth': '+6% this week',
    'dashboard.opportunity1.title': 'Document management system',
    'dashboard.opportunity1.client': 'Ministry of Education',
    'dashboard.opportunity2.title': 'Cloud infrastructure',
    'dashboard.opportunity2.client': 'Île‑de‑France Region',
    'dashboard.opportunity3.title': 'E‑learning platform',
    'dashboard.opportunity3.client': 'University of Lyon',
    
    // CGU Page
    'cgu.title': 'Terms & Conditions',
    'cgu.lastUpdate': 'Last update',
    
    // Product Page
    'product.badge': 'Artificial Intelligence • Public Procurement',
    'product.hero.title': 'The most advanced AI platform for public procurement',
    'product.hero.subtitle': 'Discover how our artificial intelligence revolutionises the detection and analysis of public tenders to maximise your chances of success.',
    'product.features.title': 'Key',
    'product.features.title.highlight': 'features',
    'product.features.subtitle': 'A complete suite of AI tools to transform your approach to public procurement',
    'product.benefits.title': 'Measurable',
    'product.benefits.title.highlight': 'results',
    // Product demo (personas)
    'product.demo.badge': 'Product demo',
    'product.demo.title': 'Solutions by professional profile',
    'product.demo.subtitle': 'Discover how Eligibly adapts to your role in the public procurement ecosystem',
    'product.demo.profileSelected': 'Profile selected',
    'product.demo.benefits': 'Key benefits',
    'product.demo.actions': 'Actions in Eligibly',
    'product.demo.cta.title': 'Eligibly adapts to your role',
    'product.demo.cta.subtitle': 'Discover your personalised business scenario in a demo tailored to your specific needs.',
    'product.demo.cta.button': 'Book a personalised demo',
    // Personas
    'product.demo.persona.acheteur.title': 'Public procurement manager / Public buyer',
    'product.demo.persona.acheteur.desc': 'You oversee purchases and select the best providers for your authority or administration. Your challenge: quickly identify the most relevant companies and secure your decisions.',
    'product.demo.persona.acheteur.b1': 'Automatically compare your suppliers',
    'product.demo.persona.acheteur.b2': 'Analyse and rank applications in one click',
    'product.demo.persona.acheteur.b3': 'Optimise your purchasing for greater efficiency',
    'product.demo.persona.acheteur.a1': 'Identify and qualify your ideal providers',
    'product.demo.persona.acheteur.a2': 'Easily manage and track your shortlists',
    'product.demo.persona.acheteur.a3': 'Automatically check technical and administrative compliance',

    'product.demo.persona.chef.title': 'Project manager / Tender lead',
    'product.demo.persona.chef.desc': 'You coordinate public procurement projects and lead the consultations. Your challenge: ensure consistency between business needs and market offers while meeting deadlines.',
    'product.demo.persona.chef.b1': 'Consolidated overview of all ongoing tenders',
    'product.demo.persona.chef.b2': 'Objective, automated comparison of responses',
    'product.demo.persona.chef.b3': 'Full traceability of decisions and criteria',
    'product.demo.persona.chef.a1': 'Compare and consolidate different responses',
    'product.demo.persona.chef.a2': 'Validate the match between offer and business need',
    'product.demo.persona.chef.a3': 'Coordinate teams and meet deadlines',

    'product.demo.persona.commercial.title': 'Sales manager / Business developer',
    'product.demo.persona.commercial.desc': 'You grow your SME/ESN client portfolio in the public sector. Your goal: detect the most promising opportunities and maximise your win rates.',
    'product.demo.persona.commercial.b1': 'Automatic detection of matching tenders',
    'product.demo.persona.commercial.b2': 'Real‑time relevance score',
    'product.demo.persona.commercial.b3': 'Sector‑based personalised alerts',
    'product.demo.persona.commercial.a1': 'Filter and monitor opportunities by sector',
    'product.demo.persona.commercial.a2': 'Analyse competitors and selection criteria',
    'product.demo.persona.commercial.a3': 'Propose a personalised response strategy',

    'product.demo.persona.consultant.title': 'Consultant / Consulting firm',
    'product.demo.persona.consultant.desc': 'You support your clients in their public procurement growth strategy. Your added value: expertise and strategic monitoring to maximise their success.',
    'product.demo.persona.consultant.b1': 'Comprehensive sector monitoring',
    'product.demo.persona.consultant.b2': 'Advanced competitive analysis',
    'product.demo.persona.consultant.b3': 'Automated client reports',
    'product.demo.persona.consultant.a1': 'Carry out complete, targeted market monitoring',
    'product.demo.persona.consultant.a2': 'Prepare optimised strategic responses',
    'product.demo.persona.consultant.a3': 'Download and analyse relevant tender documents',

    // Solutions Page  
    'solutions.badge': 'Tailored solutions',
    'solutions.hero.title': 'A solution for every',
    'solutions.hero.title.highlight': 'professional profile',
    'solutions.hero.subtitle': 'Our AI adapts to the specific needs of your sector and role to maximise your commercial performance.',
    'solutions.commercial.title': 'Sales teams',
    'solutions.commercial.subtitle': 'Sales & Business Developers',
    'solutions.commercial.description': 'Automatically detect opportunities that perfectly match your offering and maximise your conversion rate.',
    'solutions.commercial.cta': 'Boost my sales',
    'solutions.consultant.title': 'Consultants & AMO',
    'solutions.consultant.subtitle': 'Project management assistance',
    'solutions.consultant.description': 'Support your clients with data‑driven expertise and comprehensive monitoring of public markets in your sector.',
    'solutions.consultant.cta': 'Enrich my expertise',
    'solutions.public.title': 'Public buyers',
    'solutions.public.subtitle': 'Local authorities & administrations',
    'solutions.public.description': 'Optimise your public procurement through market intelligence and automated benchmarks from our AI.',
    'solutions.public.cta': 'Optimise my procurement',
    'solutions.usecases.title': 'Client',
    'solutions.usecases.title.highlight': 'use cases',
    'solutions.usecases.subtitle': 'Discover how our clients transform their commercial performance',
    
    // Pricing Page
    'pricing.badge': 'Transparent pricing',
    'pricing.hero.title': 'Choose your',
    'pricing.hero.title.highlight': 'perfect plan',
    'pricing.hero.subtitle': 'Simple and transparent pricing. Start today, scale as you grow. No commitment.',
    'pricing.guarantee.title': '30‑day money‑back guarantee',
    'pricing.guarantee.subtitle': 'We are confident our AI will transform your commercial monitoring. If you are not satisfied, we will refund you in full.',
    // Plans
    'pricing.plan.starter.name': 'Starter',
    'pricing.plan.starter.price': '49',
    'pricing.plan.starter.period': '/month',
    'pricing.plan.starter.description': 'Perfect for small businesses getting started',
    'pricing.plan.starter.cta': 'Start now',
    'pricing.plan.starter.features.1': 'Up to 50 alerts/month',
    'pricing.plan.starter.features.2': '3 monitoring sectors',
    'pricing.plan.starter.features.3': 'Basic AI scoring',
    'pricing.plan.starter.features.4': 'Email support',
    'pricing.plan.starter.features.5': 'Simple dashboard',
    'pricing.plan.starter.features.6': 'Email alerts',
    
    'pricing.plan.professional.name': 'Professional',
    'pricing.plan.professional.badge': 'Most popular',
    'pricing.plan.professional.price': '149',
    'pricing.plan.professional.period': '/month',
    'pricing.plan.professional.description': 'For growing companies',
    'pricing.plan.professional.cta': 'Try 14 days',
    'pricing.plan.professional.features.1': 'Unlimited alerts',
    'pricing.plan.professional.features.2': 'All sectors monitored',
    'pricing.plan.professional.features.3': 'Advanced AI scoring + competitor analysis',
    'pricing.plan.professional.features.4': 'Priority support',
    'pricing.plan.professional.features.5': 'Full dashboard',
    'pricing.plan.professional.features.6': 'Slack/Teams/Email alerts',
    'pricing.plan.professional.features.7': 'CRM integrations',
    'pricing.plan.professional.features.8': 'Custom reports',
    'pricing.plan.professional.features.9': 'API available',
    
    'pricing.plan.enterprise.name': 'Enterprise',
    'pricing.plan.enterprise.badge': 'Premium',
    'pricing.plan.enterprise.price': 'Custom',
    'pricing.plan.enterprise.period': '',
    'pricing.plan.enterprise.description': 'Custom solution for large organisations',
    'pricing.plan.enterprise.cta': 'Contact us',
    'pricing.plan.enterprise.features.1': 'Custom volume',
    'pricing.plan.enterprise.features.2': 'Tailored monitoring',
    'pricing.plan.enterprise.features.3': 'Custom AI + machine learning',
    'pricing.plan.enterprise.features.4': 'Dedicated account manager',
    'pricing.plan.enterprise.features.5': 'Custom dashboards',
    'pricing.plan.enterprise.features.6': 'Full integrations',
    'pricing.plan.enterprise.features.7': 'Team training',
    'pricing.plan.enterprise.features.8': 'SLA guaranteed',
    'pricing.plan.enterprise.features.9': 'On‑premise deployment possible',
    
    // FAQ
    'pricing.faq.title': 'Frequently',
    'pricing.faq.title.highlight': 'asked questions',
    'pricing.faq.q1.title': 'Can I change plan anytime?',
    'pricing.faq.q1.desc': 'Yes, you can upgrade or downgrade at any time. Changes take effect immediately.',
    'pricing.faq.q2.title': 'Are there any setup fees?',
    'pricing.faq.q2.desc': 'No setup fees. You only pay your monthly subscription, no commitment.',
    'pricing.faq.q3.title': 'What happens after the trial?',
    'pricing.faq.q3.desc': 'You can continue with a paid plan or revert to a limited entry plan. No credit card required for the trial.',
    'pricing.faq.q4.title': 'Is technical support included?',
    'pricing.faq.q4.desc': 'Yes, all plans include support. Pro+ plan benefits from priority support.',
    
    // Bottom CTA metrics
    'pricing.bottom.trialDays': '14 days',
    'pricing.bottom.trialLabel': 'Trial',
    'pricing.bottom.setupFee': '€0',
    'pricing.bottom.setupLabel': 'Setup fee',
    'pricing.bottom.supportHours': '24/7',
    'pricing.bottom.supportLabel': 'Support included',
    
    // Resources Page
    'resources.badge': 'Resource centre',
    'resources.hero.title': 'Everything to succeed in your',
    'resources.hero.title.highlight': 'public procurement',
    'resources.hero.subtitle': 'Guides, tutorials, analyses and best practices to maximise your commercial performance in public procurement.',
    'resources.featured.title': 'Featured article',
    'resources.featured.subtitle': 'Our selection of the week',
    'resources.articles.title': 'Latest articles',
    'resources.articles.subtitle': 'Expert advice and analysis',
    'resources.guides.title': 'Guides and',
    'resources.guides.title.highlight': 'templates',
    'resources.guides.subtitle': 'Practical resources to download',
    'resources.videos.title': 'Video',
    'resources.videos.title.highlight': 'tutorials',
    'resources.videos.subtitle': 'Learn to use Eligibly.ai effectively',
    // Resources Coming soon
    'resources.comingSoon': 'Coming soon',
    'resources.dontMiss': "Don't miss the",
    'resources.notifyMe': 'Notify me',
    'resources.emailPlaceholder': 'Your email address',
    'resources.notifyThanks': 'Thank you! You will be notified as soon as it is released.',
    'resources.notifyHelp': 'Receive an email as soon as a new resource is available',
    // Resources extra
    'resources.hero.blurb': 'We are preparing a comprehensive resource library to help you excel in public procurement. Guides, webinars, templates and exclusive analyses.',
    'resources.upcoming.title': 'What to expect',
    'resources.upcoming.subtitle': 'Discover the exclusive resources we are preparing to transform your approach to public procurement',
    'resources.stats.preparing': 'In preparation',
    'resources.contact.title': 'A specific question?',
    'resources.contact.subtitle': 'While we prepare resources, our team is here to help you',
    'resources.contact.supportEmail': 'Email support',
    'resources.contact.response': 'Reply within 24h',
    'resources.contact.community': 'Community',
    'resources.contact.chat': 'Professional discussions',
    'resources.contact.join': 'Join',
    'resources.contact.consulting': 'Consulting',
    'resources.contact.advice': 'Personalised advice',
    'resources.contact.book': 'Book a call',
    
    // About Page
    'about.badge': 'About Eligibly.ai',
    'about.hero.title': 'Our mission:',
    'about.hero.title.highlight': 'democratise AI',
    'about.hero.subtitle': 'We develop the most advanced artificial intelligence tools to revolutionise how organisations approach public procurement.',
    'about.vision.title': 'Our',
    'about.vision.title.highlight': 'vision',
    'about.values.title': 'Our',
    'about.values.title.highlight': 'values',
    'about.values.subtitle': 'The principles that guide each of our decisions and innovations',
    'about.team.title': 'Our',
    'about.team.title.highlight': 'team',
    'about.team.subtitle': 'Experts passionate about AI and public procurement',
    'about.security.title': 'Security and',
    'about.security.title.highlight': 'compliance',
    'about.security.subtitle': 'Your data is our absolute priority. We adhere to the highest security standards.',
    'about.hero.why': 'Why Charly by Eligibly?',
    'about.hero.desc': 'Charly by Eligibly is far more than a tool: it is your exceptional partner, your essential right‑hand to conquer public tenders thanks to Eligibly’s innovation.',
    'about.problem.title': 'The problem',
    
    // Demo Page
    'demo.badge': 'Personalised demonstration',
    'demo.hero.title': 'Discover your',
    'demo.hero.title.highlight': 'AI potential',
    'demo.hero.subtitle': 'Book your personalised 30‑minute demonstration and discover how our AI can transform your approach to public procurement.',
    'demo.form.title': 'Book your demonstration',
    'demo.form.subtitle': 'Complete this form and our experts will contact you within 2 hours',
    'demo.benefits.title': 'What you will discover',
    'demo.program.title': 'Demo programme',
    'demo.hero.detail.duration': '30 minutes sharp',
    'demo.hero.detail.slots': 'Slots available today',
    'demo.hero.detail.nocommit': 'No commitment',
    'demo.form.firstName': 'First name *',
    'demo.form.lastName': 'Last name *',
    'demo.form.email': 'Work email *',
    'demo.form.company': 'Company *',
    'demo.form.role': 'Role *',
    'demo.form.role.placeholder': 'Select your role',
    'demo.form.role.commercial': 'Sales / Business development',
    'demo.form.role.direction': 'Leadership / CEO',
    'demo.form.role.marketing': 'Marketing / Communications',
    'demo.form.role.consultant': 'Consultant / AMO',
    'demo.form.role.buyer': 'Public buyer',
    'demo.form.role.other': 'Other',
    'demo.form.sector': 'Sector',
    'demo.form.sector.placeholder': 'Choose your sector',
    'demo.form.sector.tech': 'Technology / Digital',
    'demo.form.sector.construction': 'Construction',
    'demo.form.sector.business': 'Business services',
    'demo.form.sector.health': 'Health / Medical',
    'demo.form.sector.energy': 'Energy / Environment',
    'demo.form.sector.transport': 'Transport / Logistics',
    'demo.form.sector.other': 'Other',
    'demo.form.teamSize': "Team size",
    'demo.form.teamSize.placeholder': 'Your team size',
    'demo.form.teamSize.1-10': '1–10 people',
    'demo.form.teamSize.11-50': '11–50 people',
    'demo.form.teamSize.51-200': '51–200 people',
    'demo.form.teamSize.200+': '200+ people',
    'demo.form.challenges': 'Your current challenges (optional)',
    'demo.form.challenges.placeholder': 'Describe your main challenges…',
    'demo.form.newsletter': 'Receive expert tips by email (optional)',
    'demo.form.submit': 'Book my demonstration',
    'demo.form.privacy': 'By submitting this form, you agree to be contacted by our team. Your data is protected under our ',
    'demo.form.privacy.link': 'privacy policy',
    
    // AO labels
    'ao.compatibility': 'Compatibility',
    'ao.budget': 'Budget',
    'ao.deadline': 'Deadline',
    'ao.duration': 'Duration',
    'ao.holder': 'Awardee',
    'ao.apply': 'Apply with Eligibly',
    'ao.status.published': 'published',
    'ao.status.upcoming': 'upcoming',
    'ao.aiCompatibilityScore': 'AI compatibility score',
    'ao.criteria.title': 'Evaluation criteria',
    'ao.criteria.price': 'Price',
    'ao.criteria.quality': 'Quality',
    'ao.criteria.performance': 'Performance',
    'login.subtitle': 'Access your Eligibly.ai dashboard',
    'login.welcome.title': 'Welcome to your',
    'login.welcome.title.highlight': 'AI workspace',
    'login.welcome.subtitle': 'Access your personalised dashboard and discover opportunities detected by Charly, the Eligibly AI assistant.',
    'login.demo.title': 'Discover our platform first',
    'login.demo.subtitle': 'Try all features for 7 days, no commitment',
    
    // Common elements
    'common.getStarted': 'Get started free',
    'common.bookDemo': 'Book a demo',
    'common.learnMore': 'Learn more',
    'common.download': 'Download',
    'common.readMore': 'Read more',
    'common.viewAll': 'View all',
    'common.tryFree': 'Try free',
    'common.contact': 'Contact us',
    'common.login': 'Sign in',
    'common.signUp': 'Sign up',
    'common.readArticle': 'Read article',
    'common.watchDemo': 'Watch demo',
    'common.schedule': 'Schedule',
    
    // AO results section
    'ao.results.title': 'Tender analysis results',
    'ao.results.found': 'opportunities found',
    'ao.results.avgScore': 'Average score',
    'ao.results.excellent': 'excellent',
    'ao.results.good': 'good',
    'ao.results.filters': 'Filters',
    'ao.results.search': 'Search',
    'ao.results.detailedView': 'Detailed view',
    'ao.results.viewAll': 'View all results',
    'ao.results.fullAnalysis': 'Full analysis',
    'ao.results.totalBudget': 'Total available budget',
    'ao.results.avgCompatibility': 'Average compatibility score',
    'ao.results.publishedCount': 'Published tenders (applications possible)',
    
    // Cookie Consent
    'cookies.title': 'Cookie Management',
    'cookies.description': 'We use cookies to improve your experience on our site. Some cookies are necessary for the site to function, others help us analyze traffic and personalize content.',
    'cookies.gdpr': 'GDPR Compliant - You can change your preferences at any time.',
    'cookies.customize': 'Customize',
    'cookies.necessaryOnly': 'Necessary only',
    'cookies.acceptAll': 'Accept all',
    'cookies.settings': 'Privacy Settings',
    'cookies.tabCookies': 'Cookies',
    'cookies.tabPolicy': 'Policy',
    'cookies.necessary.title': 'Necessary Cookies',
    'cookies.necessary.desc': 'Required for the site to function properly',
    'cookies.necessary.details': 'Session cookies, security, language preferences, shopping cart',
    'cookies.analytics.title': 'Analytics Cookies',
    'cookies.analytics.desc': 'Help us understand site usage',
    'cookies.analytics.details': 'Google Analytics (anonymized), audience metrics, pages visited',
    'cookies.marketing.title': 'Marketing Cookies',
    'cookies.marketing.desc': 'To personalize advertisements',
    'cookies.marketing.details': 'Social networks, targeted ads, remarketing',
    'cookies.preferences.title': 'Preference Cookies',
    'cookies.preferences.desc': 'Remember your personal choices',
    'cookies.preferences.details': 'Dark/light theme, region, display preferences',
    'cookies.policy.title': 'Our Commitment to Your Privacy',
    'cookies.policy.intro': 'Eligibly.ai respects your privacy and is committed to protecting your personal data in accordance with the General Data Protection Regulation (GDPR).',
    'cookies.policy.purposes': 'Processing Purposes',
    'cookies.policy.purpose1': 'Technical operation of the site (necessary cookies)',
    'cookies.policy.purpose2': 'Audience analysis and service improvement',
    'cookies.policy.purpose3': 'Personalization of user experience',
    'cookies.policy.purpose4': 'Marketing communication (with your consent)',
    'cookies.policy.rights': 'Your Rights',
    'cookies.policy.rightsText': 'You have the right to access, rectify, delete, port and object to your data. Contact us at: contact@eligibly.ai',
    'cookies.policy.retention': 'Retention Period',
    'cookies.policy.retentionText': 'Cookies are stored for a maximum of 13 months. Your consent is valid for 13 months and can be withdrawn at any time.',
    'cookies.cancel': 'Cancel',
    'cookies.save': 'Save Preferences',
  }
} as const;

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check localStorage first, then browser language, default to French
    const saved = secureStorage.getItem('eligibly-language') as Language;
    if (saved && (saved === 'fr' || saved === 'en')) {
      return saved;
    }
    
    // Detect browser language
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('en')) {
      return 'en';
    }
    
    return 'fr'; // Default to French
  });

  useEffect(() => {
    secureStorage.setItem('eligibly-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const dict = translations[language] as Record<string, string>;
    if (Object.prototype.hasOwnProperty.call(dict, key)) {
      return dict[key] as string; // can be empty string
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};