INSERT INTO linkedin_campaigns (linkedin_url, firstname, lastname, company, title, sector, city, step)
VALUES
  ('https://www.linkedin.com/in/alexandre-morel-renard-btp', 'Alexandre', 'Morel', 'Renard BTP', 'Gerant', 'BTP', 'Lyon', 'invitation_pending'),
  ('https://www.linkedin.com/in/camille-vidal-construction-mediterranee', 'Camille', 'Vidal', 'Construction Mediterranee', 'Directrice generale', 'BTP', 'Marseille', 'invitation_pending'),
  ('https://www.linkedin.com/in/julien-mercier-hexa-chantier', 'Julien', 'Mercier', 'Hexa Chantier', 'President', 'BTP', 'Toulouse', 'invitation_pending'),
  ('https://www.linkedin.com/in/sophie-bernard-atlantique-vrd', 'Sophie', 'Bernard', 'Atlantique VRD', 'Gerante', 'BTP', 'Nantes', 'invitation_pending'),
  ('https://www.linkedin.com/in/thomas-roussel-batipro-services', 'Thomas', 'Roussel', 'Batipro Services', 'Directeur commercial', 'BTP', 'Lille', 'invitation_pending'),
  ('https://www.linkedin.com/in/elodie-garcia-infra-sud-conseil', 'Elodie', 'Garcia', 'Infra Sud Conseil', 'Directrice AO', 'BTP', 'Montpellier', 'invitation_pending'),
  ('https://www.linkedin.com/in/benoit-chevalier-altius-travaux', 'Benoit', 'Chevalier', 'Altius Travaux', 'Gerant', 'BTP', 'Grenoble', 'invitation_pending'),
  ('https://www.linkedin.com/in/claire-perrin-urbanis-btp', 'Claire', 'Perrin', 'Urbanis BTP', 'Directrice exploitation', 'BTP', 'Nice', 'invitation_pending'),
  ('https://www.linkedin.com/in/nicolas-faure-terra-publica-tp', 'Nicolas', 'Faure', 'Terra Publica TP', 'President', 'BTP', 'Bordeaux', 'invitation_pending'),
  ('https://www.linkedin.com/in/morgane-petit-chantiers-du-forez', 'Morgane', 'Petit', 'Chantiers du Forez', 'Directrice generale', 'BTP', 'Saint-Etienne', 'invitation_pending'),
  ('https://www.linkedin.com/in/romain-leroy-bastion-genie-civil', 'Romain', 'Leroy', 'Bastion Genie Civil', 'Gerant', 'BTP', 'Rouen', 'invitation_pending'),
  ('https://www.linkedin.com/in/anais-marchand-grand-ouest-voirie', 'Anais', 'Marchand', 'Grand Ouest Voirie', 'Directrice appels d''offres', 'BTP', 'Rennes', 'invitation_pending'),
  ('https://www.linkedin.com/in/victor-lopez-delta-fondations', 'Victor', 'Lopez', 'Delta Fondations', 'Directeur developpement', 'BTP', 'Strasbourg', 'invitation_pending'),
  ('https://www.linkedin.com/in/laura-meyer-elysee-travaux-publics', 'Laura', 'Meyer', 'Elysee Travaux Publics', 'Presidente', 'BTP', 'Paris', 'invitation_pending'),
  ('https://www.linkedin.com/in/cedric-masson-rivage-construction', 'Cedric', 'Masson', 'Rivage Construction', 'Gerant', 'BTP', 'La Rochelle', 'invitation_pending'),
  ('https://www.linkedin.com/in/pauline-barbier-capstone-btp-conseil', 'Pauline', 'Barbier', 'Capstone BTP Conseil', 'Directrice marche public', 'BTP', 'Reims', 'invitation_pending'),
  ('https://www.linkedin.com/in/damien-gautier-atria-batiment', 'Damien', 'Gautier', 'Atria Batiment', 'President', 'BTP', 'Clermont-Ferrand', 'invitation_pending'),
  ('https://www.linkedin.com/in/manon-noel-poseidon-vrd', 'Manon', 'Noel', 'Poseidon VRD', 'Directrice commerciale', 'BTP', 'Toulon', 'invitation_pending'),
  ('https://www.linkedin.com/in/guillaume-hubert-occitane-amenagement', 'Guillaume', 'Hubert', 'Occitane Amenagement', 'Gerant', 'BTP', 'Perpignan', 'invitation_pending'),
  ('https://www.linkedin.com/in/sarah-colin-novalis-gros-oeuvre', 'Sarah', 'Colin', 'Novalis Gros Oeuvre', 'Directrice generale', 'BTP', 'Dijon', 'invitation_pending'),
  ('https://www.linkedin.com/in/loic-brunet-mistral-infrastructures', 'Loic', 'Brunet', 'Mistral Infrastructures', 'President', 'BTP', 'Aix-en-Provence', 'invitation_pending'),
  ('https://www.linkedin.com/in/aurelie-renaud-orizon-chantiers', 'Aurelie', 'Renaud', 'Orizon Chantiers', 'Directrice strategy AO', 'BTP', 'Angers', 'invitation_pending'),
  ('https://www.linkedin.com/in/matthieu-prevost-val-de-loire-tp', 'Matthieu', 'Prevost', 'Val de Loire TP', 'Gerant', 'BTP', 'Tours', 'invitation_pending'),
  ('https://www.linkedin.com/in/celine-guerin-mont-blanc-ouvrages', 'Celine', 'Guerin', 'Mont-Blanc Ouvrages', 'Directrice agence', 'BTP', 'Annecy', 'invitation_pending'),
  ('https://www.linkedin.com/in/hugo-lacroix-boreal-travaux', 'Hugo', 'Lacroix', 'Boreal Travaux', 'Directeur general', 'BTP', 'Metz', 'invitation_pending'),
  ('https://www.linkedin.com/in/adrien-leclerc-techpublic-solutions', 'Adrien', 'Leclerc', 'TechPublic Solutions', 'CEO', 'IT', 'Paris', 'invitation_pending'),
  ('https://www.linkedin.com/in/marion-roche-infogerance-sud', 'Marion', 'Roche', 'Infogerance Sud', 'Directrice commerciale secteur public', 'IT', 'Marseille', 'invitation_pending'),
  ('https://www.linkedin.com/in/yanis-bourdon-civisys', 'Yanis', 'Bourdon', 'Civisys', 'Business developer', 'IT', 'Lyon', 'invitation_pending'),
  ('https://www.linkedin.com/in/lucie-pons-novacollectivites', 'Lucie', 'Pons', 'NovaCollectivites', 'Directrice generale', 'IT', 'Toulouse', 'invitation_pending'),
  ('https://www.linkedin.com/in/kevin-mallet-datamarches', 'Kevin', 'Mallet', 'DataMarches', 'Co-fondateur', 'IT', 'Lille', 'invitation_pending'),
  ('https://www.linkedin.com/in/lea-garnier-asteria-esn', 'Lea', 'Garnier', 'Asteria ESN', 'Responsable developpement public', 'IT', 'Nantes', 'invitation_pending'),
  ('https://www.linkedin.com/in/maxime-riviere-hexagov-cloud', 'Maxime', 'Riviere', 'HexaGov Cloud', 'CEO', 'IT', 'Bordeaux', 'invitation_pending'),
  ('https://www.linkedin.com/in/ines-schmitt-publicis-tech-ops', 'Ines', 'Schmitt', 'Publicis Tech Ops', 'Directrice business development', 'IT', 'Strasbourg', 'invitation_pending'),
  ('https://www.linkedin.com/in/samuel-dupin-openterritoires', 'Samuel', 'Dupin', 'OpenTerritoires', 'Co-fondateur', 'IT', 'Montpellier', 'invitation_pending'),
  ('https://www.linkedin.com/in/chloe-rolland-bluesignal-numerique', 'Chloe', 'Rolland', 'BlueSignal Numerique', 'Directrice commerciale', 'IT', 'Rennes', 'invitation_pending'),
  ('https://www.linkedin.com/in/antoine-picard-agora-digital-services', 'Antoine', 'Picard', 'Agora Digital Services', 'CEO', 'IT', 'Grenoble', 'invitation_pending'),
  ('https://www.linkedin.com/in/justine-arnaud-cobalt-esn', 'Justine', 'Arnaud', 'Cobalt ESN', 'Directrice grands comptes publics', 'IT', 'Nice', 'invitation_pending'),
  ('https://www.linkedin.com/in/mehdi-santos-vertex-sector-public', 'Mehdi', 'Santos', 'Vertex Sector Public', 'Business developer', 'IT', 'Rouen', 'invitation_pending'),
  ('https://www.linkedin.com/in/eva-lemoine-capcollectif-it', 'Eva', 'Lemoine', 'CapCollectif IT', 'Directrice generale', 'IT', 'Reims', 'invitation_pending'),
  ('https://www.linkedin.com/in/quentin-caron-omnia-marches', 'Quentin', 'Caron', 'Omnia Marches', 'Head of sales', 'IT', 'Aix-en-Provence', 'invitation_pending'),
  ('https://www.linkedin.com/in/nora-besson-infracode-conseil', 'Nora', 'Besson', 'InfraCode Conseil', 'Directrice conseil', 'IT', 'Clermont-Ferrand', 'invitation_pending'),
  ('https://www.linkedin.com/in/theo-geoffroy-sirius-collectivites', 'Theo', 'Geoffroy', 'Sirius Collectivites', 'CEO', 'IT', 'Tours', 'invitation_pending'),
  ('https://www.linkedin.com/in/alice-robin-polaris-public-cloud', 'Alice', 'Robin', 'Polaris Public Cloud', 'Directrice partenariats', 'IT', 'Annecy', 'invitation_pending'),
  ('https://www.linkedin.com/in/bilal-fernandez-synapse-territoriale', 'Bilal', 'Fernandez', 'Synapse Territoriale', 'Business developer secteur public', 'IT', 'Toulon', 'invitation_pending'),
  ('https://www.linkedin.com/in/meline-moulin-kappa-it-conseil', 'Meline', 'Moulin', 'Kappa IT Conseil', 'Directrice generale', 'IT', 'Metz', 'invitation_pending'),
  ('https://www.linkedin.com/in/corentin-bailly-infocite-services', 'Corentin', 'Bailly', 'Infocite Services', 'CEO', 'IT', 'Orleans', 'invitation_pending'),
  ('https://www.linkedin.com/in/amandine-jacquet-pixel-public', 'Amandine', 'Jacquet', 'Pixel Public', 'Directrice commerciale', 'IT', 'Dijon', 'invitation_pending'),
  ('https://www.linkedin.com/in/walid-perrot-operatix-esn', 'Walid', 'Perrot', 'Operatix ESN', 'Responsable marche public', 'IT', 'Angers', 'invitation_pending'),
  ('https://www.linkedin.com/in/noemie-morin-signalia-govtech', 'Noemie', 'Morin', 'Signalia GovTech', 'Co-fondatrice', 'IT', 'Perpignan', 'invitation_pending'),
  ('https://www.linkedin.com/in/florian-lambert-civicflow-numerique', 'Florian', 'Lambert', 'CivicFlow Numerique', 'CEO', 'IT', 'La Rochelle', 'invitation_pending'),
  ('https://www.linkedin.com/in/isabelle-pascal-forma-pro-conseil', 'Isabelle', 'Pascal', 'Forma Pro Conseil', 'Directrice Qualiopi', 'Formation', 'Paris', 'invitation_pending'),
  ('https://www.linkedin.com/in/jerome-breton-academie-des-marches', 'Jerome', 'Breton', 'Academie des Marches', 'Gerant', 'Formation', 'Lyon', 'invitation_pending'),
  ('https://www.linkedin.com/in/nadia-gilbert-campus-achat-public', 'Nadia', 'Gilbert', 'Campus Achat Public', 'Directrice generale', 'Formation', 'Marseille', 'invitation_pending'),
  ('https://www.linkedin.com/in/frederic-navarro-qualiopi-experts-france', 'Frederic', 'Navarro', 'Qualiopi Experts France', 'President', 'Formation', 'Toulouse', 'invitation_pending'),
  ('https://www.linkedin.com/in/pauline-henry-of-performance', 'Pauline', 'Henry', 'OF Performance', 'Directrice pedagogique', 'Formation', 'Lille', 'invitation_pending'),
  ('https://www.linkedin.com/in/karim-marty-cap-opco-formation', 'Karim', 'Marty', 'Cap OPCO Formation', 'Gerant', 'Formation', 'Nantes', 'invitation_pending'),
  ('https://www.linkedin.com/in/valerie-dumas-institut-reponse-ao', 'Valerie', 'Dumas', 'Institut Reponse AO', 'Directrice Qualite', 'Formation', 'Bordeaux', 'invitation_pending'),
  ('https://www.linkedin.com/in/cyril-pelletier-atelier-formation-territoires', 'Cyril', 'Pelletier', 'Atelier Formation Territoires', 'President', 'Formation', 'Montpellier', 'invitation_pending'),
  ('https://www.linkedin.com/in/aude-lefort-forma-publica', 'Aude', 'Lefort', 'Forma Publica', 'Directrice generale', 'Formation', 'Rennes', 'invitation_pending'),
  ('https://www.linkedin.com/in/rachid-boulanger-opco-competences-conseil', 'Rachid', 'Boulanger', 'OPCO Competences Conseil', 'Gerant', 'Formation', 'Grenoble', 'invitation_pending'),
  ('https://www.linkedin.com/in/delphine-vernet-academie-qualiopi-sud', 'Delphine', 'Vernet', 'Academie Qualiopi Sud', 'Directrice developpement', 'Formation', 'Nice', 'invitation_pending'),
  ('https://www.linkedin.com/in/stephane-gil-campus-conseil-certification', 'Stephane', 'Gil', 'Campus Conseil Certification', 'President', 'Formation', 'Rouen', 'invitation_pending'),
  ('https://www.linkedin.com/in/marina-blanc-nextstep-formation', 'Marina', 'Blanc', 'NextStep Formation', 'Directrice generale', 'Formation', 'Strasbourg', 'invitation_pending'),
  ('https://www.linkedin.com/in/olivier-pruvost-of-marche-memoire', 'Olivier', 'Pruvost', 'OF Marche & Memoire', 'Gerant', 'Formation', 'Reims', 'invitation_pending'),
  ('https://www.linkedin.com/in/sabrina-costa-convergence-pedagogie', 'Sabrina', 'Costa', 'Convergence Pedagogie', 'Directrice Qualite', 'Formation', 'Aix-en-Provence', 'invitation_pending'),
  ('https://www.linkedin.com/in/david-julien-reference-formation-publique', 'David', 'Julien', 'Reference Formation Publique', 'President', 'Formation', 'Clermont-Ferrand', 'invitation_pending'),
  ('https://www.linkedin.com/in/mylene-etienne-expertise-opco-conseil', 'Mylene', 'Etienne', 'Expertise OPCO Conseil', 'Directrice generale', 'Formation', 'Tours', 'invitation_pending'),
  ('https://www.linkedin.com/in/brice-texier-campus-reussite-ao', 'Brice', 'Texier', 'Campus Reussite AO', 'Gerant', 'Formation', 'Annecy', 'invitation_pending'),
  ('https://www.linkedin.com/in/helene-imbert-qualiformation-360', 'Helene', 'Imbert', 'QualiFormation 360', 'Directrice Qualiopi', 'Formation', 'Dijon', 'invitation_pending'),
  ('https://www.linkedin.com/in/pascal-devaux-institut-des-dossiers-publics', 'Pascal', 'Devaux', 'Institut des Dossiers Publics', 'President', 'Formation', 'Angers', 'invitation_pending')
ON CONFLICT (linkedin_url) DO UPDATE
SET firstname = EXCLUDED.firstname,
    lastname = EXCLUDED.lastname,
    company = EXCLUDED.company,
    title = EXCLUDED.title,
    sector = EXCLUDED.sector,
    city = EXCLUDED.city,
    updated_at = NOW();
