/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AlternativesPrimoleadExpertsComptablesRouteImport } from './routes/alternatives-primolead-experts-comptables'
import { Route as CanauxActivationRouteImport } from './routes/canaux-activation'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ImageDeMarqueExpertComptableRouteImport } from './routes/image-de-marque-expert-comptable'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as LeadsExpertsComptablesRouteImport } from './routes/leads-experts-comptables'
import { Route as MarqueEtVisibiliteExpertComptableRouteImport } from './routes/marque-et-visibilite-expert-comptable'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NewsletterConfigRouteImport } from './routes/newsletter-config'
import { Route as PourquoiCeLeadEstPrioritaireRouteImport } from './routes/pourquoi-ce-lead-est-prioritaire'
import { Route as PresenceDigitaleCabinetComptableRouteImport } from './routes/presence-digitale-cabinet-comptable'
import { Route as ProduitRouteImport } from './routes/produit'
import { Route as ProspectionCabinetComptableRouteImport } from './routes/prospection-cabinet-comptable'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as SalesAssistantRouteImport } from './routes/sales-assistant'
import { Route as SimulateurRoiIaCabinetRouteImport } from './routes/simulateur-roi-ia-cabinet'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VisibiliteExpertComptableRouteImport } from './routes/visibilite-expert-comptable'
import { Route as Blog5LeviersCroissanceCabinetExpertiseComptableRouteImport } from './routes/blog/5-leviers-croissance-cabinet-expertise-comptable'
import { Route as BlogBarometreAcquisitionCabinetEc2026RouteImport } from './routes/blog/barometre-acquisition-cabinet-ec-2026'
import { Route as BlogBarometreImmatriculationsJuillet2026RouteImport } from './routes/blog/barometre-immatriculations-juillet-2026'
import { Route as BlogCasClientEmpartnersRouteImport } from './routes/blog/cas-client-empartners'
import { Route as BlogCoutAcquisitionClientCabinetComptableRouteImport } from './routes/blog/cout-acquisition-client-cabinet-comptable'
import { Route as BlogCreationsEntreprisesFrance2025RouteImport } from './routes/blog/creations-entreprises-france-2025'
import { Route as BlogCreerSiteWebExpertComptableGuideRouteImport } from './routes/blog/creer-site-web-expert-comptable-guide'
import { Route as BlogFichierSiretVsPlanActionComptableRouteImport } from './routes/blog/fichier-siret-vs-plan-action-comptable'
import { Route as BlogGuideDemarchageClientExpertComptableRouteImport } from './routes/blog/guide-demarchage-client-expert-comptable'
import { Route as BlogIcpCabinetExpertiseComptableRouteImport } from './routes/blog/icp-cabinet-expertise-comptable'
import { Route as BlogLexiqueMarketingExpertComptableRouteImport } from './routes/blog/lexique-marketing-expert-comptable'
import { Route as BlogModerniserCabinetEtatLieux2026RouteImport } from './routes/blog/moderniser-cabinet-etat-lieux-2026'
import { Route as BlogModerniserCabinetExpertiseComptableIaRouteImport } from './routes/blog/moderniser-cabinet-expertise-comptable-ia'
import { Route as BlogObservatoireSasuSasJuin2026RouteImport } from './routes/blog/observatoire-sasu-sas-juin-2026'
import { Route as BlogPlaybookProspectionCabinetEc2026RouteImport } from './routes/blog/playbook-prospection-cabinet-ec-2026'
import { Route as BlogReferencementLocalExpertComptableRouteImport } from './routes/blog/referencement-local-expert-comptable'
import { Route as CabinetGlossaireRouteImport } from './routes/cabinet/glossaire'
import { Route as VerticalesBtpArtisansRouteImport } from './routes/verticales/btp-artisans'
import { Route as VerticalesECommerceRouteImport } from './routes/verticales/e-commerce'
import { Route as VerticalesHoldingsGroupesRouteImport } from './routes/verticales/holdings-groupes'
import { Route as VerticalesProfessionsLiberalesSanteRouteImport } from './routes/verticales/professions-liberales-sante'
import { Route as VerticalesRestaurationChrRouteImport } from './routes/verticales/restauration-chr'
import { Route as VerticalesSasuTechRouteImport } from './routes/verticales/sasu-tech'
import { Route as WaitlistSuccessRouteImport } from './routes/waitlist/success'
import { Route as CabinetCasUsageIndexRouteImport } from './routes/cabinet/cas-usage/index'
import { Route as CabinetCasUsageCabinet8CollaborateursDepartementRouteImport } from './routes/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
import { Route as CabinetCasUsageCabinetFullRemoteStartupsEcommerceRouteImport } from './routes/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
import { Route as CabinetCasUsageCabinetSpecialiseRestaurationRouteImport } from './routes/cabinet/cas-usage/cabinet-specialise-restauration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativesPrimoleadExpertsComptablesRoute =
  AlternativesPrimoleadExpertsComptablesRouteImport.update({
    id: '/alternatives-primolead-experts-comptables',
    path: '/alternatives-primolead-experts-comptables',
    getParentRoute: () => rootRouteImport,
  } as any)
const CanauxActivationRoute = CanauxActivationRouteImport.update({
  id: '/canaux-activation',
  path: '/canaux-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageDeMarqueExpertComptableRoute =
  ImageDeMarqueExpertComptableRouteImport.update({
    id: '/image-de-marque-expert-comptable',
    path: '/image-de-marque-expert-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsExpertsComptablesRoute = LeadsExpertsComptablesRouteImport.update({
  id: '/leads-experts-comptables',
  path: '/leads-experts-comptables',
  getParentRoute: () => rootRouteImport,
} as any)
const MarqueEtVisibiliteExpertComptableRoute =
  MarqueEtVisibiliteExpertComptableRouteImport.update({
    id: '/marque-et-visibilite-expert-comptable',
    path: '/marque-et-visibilite-expert-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfigRoute = NewsletterConfigRouteImport.update({
  id: '/newsletter-config',
  path: '/newsletter-config',
  getParentRoute: () => rootRouteImport,
} as any)
const PourquoiCeLeadEstPrioritaireRoute =
  PourquoiCeLeadEstPrioritaireRouteImport.update({
    id: '/pourquoi-ce-lead-est-prioritaire',
    path: '/pourquoi-ce-lead-est-prioritaire',
    getParentRoute: () => rootRouteImport,
  } as any)
const PresenceDigitaleCabinetComptableRoute =
  PresenceDigitaleCabinetComptableRouteImport.update({
    id: '/presence-digitale-cabinet-comptable',
    path: '/presence-digitale-cabinet-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProduitRoute = ProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionCabinetComptableRoute =
  ProspectionCabinetComptableRouteImport.update({
    id: '/prospection-cabinet-comptable',
    path: '/prospection-cabinet-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAssistantRoute = SalesAssistantRouteImport.update({
  id: '/sales-assistant',
  path: '/sales-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoiIaCabinetRoute = SimulateurRoiIaCabinetRouteImport.update({
  id: '/simulateur-roi-ia-cabinet',
  path: '/simulateur-roi-ia-cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VisibiliteExpertComptableRoute =
  VisibiliteExpertComptableRouteImport.update({
    id: '/visibilite-expert-comptable',
    path: '/visibilite-expert-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const Blog5LeviersCroissanceCabinetExpertiseComptableRoute =
  Blog5LeviersCroissanceCabinetExpertiseComptableRouteImport.update({
    id: '/blog/5-leviers-croissance-cabinet-expertise-comptable',
    path: '/blog/5-leviers-croissance-cabinet-expertise-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBarometreAcquisitionCabinetEc2026Route =
  BlogBarometreAcquisitionCabinetEc2026RouteImport.update({
    id: '/blog/barometre-acquisition-cabinet-ec-2026',
    path: '/blog/barometre-acquisition-cabinet-ec-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBarometreImmatriculationsJuillet2026Route =
  BlogBarometreImmatriculationsJuillet2026RouteImport.update({
    id: '/blog/barometre-immatriculations-juillet-2026',
    path: '/blog/barometre-immatriculations-juillet-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCasClientEmpartnersRoute = BlogCasClientEmpartnersRouteImport.update({
  id: '/blog/cas-client-empartners',
  path: '/blog/cas-client-empartners',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCoutAcquisitionClientCabinetComptableRoute =
  BlogCoutAcquisitionClientCabinetComptableRouteImport.update({
    id: '/blog/cout-acquisition-client-cabinet-comptable',
    path: '/blog/cout-acquisition-client-cabinet-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCreationsEntreprisesFrance2025Route =
  BlogCreationsEntreprisesFrance2025RouteImport.update({
    id: '/blog/creations-entreprises-france-2025',
    path: '/blog/creations-entreprises-france-2025',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCreerSiteWebExpertComptableGuideRoute =
  BlogCreerSiteWebExpertComptableGuideRouteImport.update({
    id: '/blog/creer-site-web-expert-comptable-guide',
    path: '/blog/creer-site-web-expert-comptable-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFichierSiretVsPlanActionComptableRoute =
  BlogFichierSiretVsPlanActionComptableRouteImport.update({
    id: '/blog/fichier-siret-vs-plan-action-comptable',
    path: '/blog/fichier-siret-vs-plan-action-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGuideDemarchageClientExpertComptableRoute =
  BlogGuideDemarchageClientExpertComptableRouteImport.update({
    id: '/blog/guide-demarchage-client-expert-comptable',
    path: '/blog/guide-demarchage-client-expert-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIcpCabinetExpertiseComptableRoute =
  BlogIcpCabinetExpertiseComptableRouteImport.update({
    id: '/blog/icp-cabinet-expertise-comptable',
    path: '/blog/icp-cabinet-expertise-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogLexiqueMarketingExpertComptableRoute =
  BlogLexiqueMarketingExpertComptableRouteImport.update({
    id: '/blog/lexique-marketing-expert-comptable',
    path: '/blog/lexique-marketing-expert-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogModerniserCabinetEtatLieux2026Route =
  BlogModerniserCabinetEtatLieux2026RouteImport.update({
    id: '/blog/moderniser-cabinet-etat-lieux-2026',
    path: '/blog/moderniser-cabinet-etat-lieux-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogModerniserCabinetExpertiseComptableIaRoute =
  BlogModerniserCabinetExpertiseComptableIaRouteImport.update({
    id: '/blog/moderniser-cabinet-expertise-comptable-ia',
    path: '/blog/moderniser-cabinet-expertise-comptable-ia',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogObservatoireSasuSasJuin2026Route =
  BlogObservatoireSasuSasJuin2026RouteImport.update({
    id: '/blog/observatoire-sasu-sas-juin-2026',
    path: '/blog/observatoire-sasu-sas-juin-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPlaybookProspectionCabinetEc2026Route =
  BlogPlaybookProspectionCabinetEc2026RouteImport.update({
    id: '/blog/playbook-prospection-cabinet-ec-2026',
    path: '/blog/playbook-prospection-cabinet-ec-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReferencementLocalExpertComptableRoute =
  BlogReferencementLocalExpertComptableRouteImport.update({
    id: '/blog/referencement-local-expert-comptable',
    path: '/blog/referencement-local-expert-comptable',
    getParentRoute: () => rootRouteImport,
  } as any)
const CabinetGlossaireRoute = CabinetGlossaireRouteImport.update({
  id: '/cabinet/glossaire',
  path: '/cabinet/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalesBtpArtisansRoute = VerticalesBtpArtisansRouteImport.update({
  id: '/verticales/btp-artisans',
  path: '/verticales/btp-artisans',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalesECommerceRoute = VerticalesECommerceRouteImport.update({
  id: '/verticales/e-commerce',
  path: '/verticales/e-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalesHoldingsGroupesRoute =
  VerticalesHoldingsGroupesRouteImport.update({
    id: '/verticales/holdings-groupes',
    path: '/verticales/holdings-groupes',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalesProfessionsLiberalesSanteRoute =
  VerticalesProfessionsLiberalesSanteRouteImport.update({
    id: '/verticales/professions-liberales-sante',
    path: '/verticales/professions-liberales-sante',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalesRestaurationChrRoute =
  VerticalesRestaurationChrRouteImport.update({
    id: '/verticales/restauration-chr',
    path: '/verticales/restauration-chr',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalesSasuTechRoute = VerticalesSasuTechRouteImport.update({
  id: '/verticales/sasu-tech',
  path: '/verticales/sasu-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistSuccessRoute = WaitlistSuccessRouteImport.update({
  id: '/waitlist/success',
  path: '/waitlist/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetCasUsageIndexRoute = CabinetCasUsageIndexRouteImport.update({
  id: '/cabinet/cas-usage/',
  path: '/cabinet/cas-usage/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetCasUsageCabinet8CollaborateursDepartementRoute =
  CabinetCasUsageCabinet8CollaborateursDepartementRouteImport.update({
    id: '/cabinet/cas-usage/cabinet-8-collaborateurs-departement',
    path: '/cabinet/cas-usage/cabinet-8-collaborateurs-departement',
    getParentRoute: () => rootRouteImport,
  } as any)
const CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute =
  CabinetCasUsageCabinetFullRemoteStartupsEcommerceRouteImport.update({
    id: '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce',
    path: '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce',
    getParentRoute: () => rootRouteImport,
  } as any)
const CabinetCasUsageCabinetSpecialiseRestaurationRoute =
  CabinetCasUsageCabinetSpecialiseRestaurationRouteImport.update({
    id: '/cabinet/cas-usage/cabinet-specialise-restauration',
    path: '/cabinet/cas-usage/cabinet-specialise-restauration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/alternatives-primolead-experts-comptables': typeof AlternativesPrimoleadExpertsComptablesRoute
  '/canaux-activation': typeof CanauxActivationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/demo': typeof DemoRoute
  '/image-de-marque-expert-comptable': typeof ImageDeMarqueExpertComptableRoute
  '/inscription': typeof InscriptionRoute
  '/leads-experts-comptables': typeof LeadsExpertsComptablesRoute
  '/marque-et-visibilite-expert-comptable': typeof MarqueEtVisibiliteExpertComptableRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/newsletter': typeof NewsletterRoute
  '/newsletter-config': typeof NewsletterConfigRoute
  '/pourquoi-ce-lead-est-prioritaire': typeof PourquoiCeLeadEstPrioritaireRoute
  '/presence-digitale-cabinet-comptable': typeof PresenceDigitaleCabinetComptableRoute
  '/produit': typeof ProduitRoute
  '/prospection-cabinet-comptable': typeof ProspectionCabinetComptableRoute
  '/ressources': typeof RessourcesRoute
  '/sales-assistant': typeof SalesAssistantRoute
  '/simulateur-roi-ia-cabinet': typeof SimulateurRoiIaCabinetRoute
  '/solutions': typeof SolutionsRoute
  '/tarifs': typeof TarifsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/visibilite-expert-comptable': typeof VisibiliteExpertComptableRoute
  '/blog/5-leviers-croissance-cabinet-expertise-comptable': typeof Blog5LeviersCroissanceCabinetExpertiseComptableRoute
  '/blog/barometre-acquisition-cabinet-ec-2026': typeof BlogBarometreAcquisitionCabinetEc2026Route
  '/blog/barometre-immatriculations-juillet-2026': typeof BlogBarometreImmatriculationsJuillet2026Route
  '/blog/cas-client-empartners': typeof BlogCasClientEmpartnersRoute
  '/blog/cout-acquisition-client-cabinet-comptable': typeof BlogCoutAcquisitionClientCabinetComptableRoute
  '/blog/creations-entreprises-france-2025': typeof BlogCreationsEntreprisesFrance2025Route
  '/blog/creer-site-web-expert-comptable-guide': typeof BlogCreerSiteWebExpertComptableGuideRoute
  '/blog/fichier-siret-vs-plan-action-comptable': typeof BlogFichierSiretVsPlanActionComptableRoute
  '/blog/guide-demarchage-client-expert-comptable': typeof BlogGuideDemarchageClientExpertComptableRoute
  '/blog/icp-cabinet-expertise-comptable': typeof BlogIcpCabinetExpertiseComptableRoute
  '/blog/lexique-marketing-expert-comptable': typeof BlogLexiqueMarketingExpertComptableRoute
  '/blog/moderniser-cabinet-etat-lieux-2026': typeof BlogModerniserCabinetEtatLieux2026Route
  '/blog/moderniser-cabinet-expertise-comptable-ia': typeof BlogModerniserCabinetExpertiseComptableIaRoute
  '/blog/observatoire-sasu-sas-juin-2026': typeof BlogObservatoireSasuSasJuin2026Route
  '/blog/playbook-prospection-cabinet-ec-2026': typeof BlogPlaybookProspectionCabinetEc2026Route
  '/blog/referencement-local-expert-comptable': typeof BlogReferencementLocalExpertComptableRoute
  '/cabinet/glossaire': typeof CabinetGlossaireRoute
  '/verticales/btp-artisans': typeof VerticalesBtpArtisansRoute
  '/verticales/e-commerce': typeof VerticalesECommerceRoute
  '/verticales/holdings-groupes': typeof VerticalesHoldingsGroupesRoute
  '/verticales/professions-liberales-sante': typeof VerticalesProfessionsLiberalesSanteRoute
  '/verticales/restauration-chr': typeof VerticalesRestaurationChrRoute
  '/verticales/sasu-tech': typeof VerticalesSasuTechRoute
  '/waitlist/success': typeof WaitlistSuccessRoute
  '/cabinet/cas-usage/cabinet-8-collaborateurs-departement': typeof CabinetCasUsageCabinet8CollaborateursDepartementRoute
  '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce': typeof CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute
  '/cabinet/cas-usage/cabinet-specialise-restauration': typeof CabinetCasUsageCabinetSpecialiseRestaurationRoute
  '/cabinet/cas-usage/': typeof CabinetCasUsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/alternatives-primolead-experts-comptables': typeof AlternativesPrimoleadExpertsComptablesRoute
  '/canaux-activation': typeof CanauxActivationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/demo': typeof DemoRoute
  '/image-de-marque-expert-comptable': typeof ImageDeMarqueExpertComptableRoute
  '/inscription': typeof InscriptionRoute
  '/leads-experts-comptables': typeof LeadsExpertsComptablesRoute
  '/marque-et-visibilite-expert-comptable': typeof MarqueEtVisibiliteExpertComptableRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/newsletter': typeof NewsletterRoute
  '/newsletter-config': typeof NewsletterConfigRoute
  '/pourquoi-ce-lead-est-prioritaire': typeof PourquoiCeLeadEstPrioritaireRoute
  '/presence-digitale-cabinet-comptable': typeof PresenceDigitaleCabinetComptableRoute
  '/produit': typeof ProduitRoute
  '/prospection-cabinet-comptable': typeof ProspectionCabinetComptableRoute
  '/ressources': typeof RessourcesRoute
  '/sales-assistant': typeof SalesAssistantRoute
  '/simulateur-roi-ia-cabinet': typeof SimulateurRoiIaCabinetRoute
  '/solutions': typeof SolutionsRoute
  '/tarifs': typeof TarifsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/visibilite-expert-comptable': typeof VisibiliteExpertComptableRoute
  '/blog/5-leviers-croissance-cabinet-expertise-comptable': typeof Blog5LeviersCroissanceCabinetExpertiseComptableRoute
  '/blog/barometre-acquisition-cabinet-ec-2026': typeof BlogBarometreAcquisitionCabinetEc2026Route
  '/blog/barometre-immatriculations-juillet-2026': typeof BlogBarometreImmatriculationsJuillet2026Route
  '/blog/cas-client-empartners': typeof BlogCasClientEmpartnersRoute
  '/blog/cout-acquisition-client-cabinet-comptable': typeof BlogCoutAcquisitionClientCabinetComptableRoute
  '/blog/creations-entreprises-france-2025': typeof BlogCreationsEntreprisesFrance2025Route
  '/blog/creer-site-web-expert-comptable-guide': typeof BlogCreerSiteWebExpertComptableGuideRoute
  '/blog/fichier-siret-vs-plan-action-comptable': typeof BlogFichierSiretVsPlanActionComptableRoute
  '/blog/guide-demarchage-client-expert-comptable': typeof BlogGuideDemarchageClientExpertComptableRoute
  '/blog/icp-cabinet-expertise-comptable': typeof BlogIcpCabinetExpertiseComptableRoute
  '/blog/lexique-marketing-expert-comptable': typeof BlogLexiqueMarketingExpertComptableRoute
  '/blog/moderniser-cabinet-etat-lieux-2026': typeof BlogModerniserCabinetEtatLieux2026Route
  '/blog/moderniser-cabinet-expertise-comptable-ia': typeof BlogModerniserCabinetExpertiseComptableIaRoute
  '/blog/observatoire-sasu-sas-juin-2026': typeof BlogObservatoireSasuSasJuin2026Route
  '/blog/playbook-prospection-cabinet-ec-2026': typeof BlogPlaybookProspectionCabinetEc2026Route
  '/blog/referencement-local-expert-comptable': typeof BlogReferencementLocalExpertComptableRoute
  '/cabinet/glossaire': typeof CabinetGlossaireRoute
  '/verticales/btp-artisans': typeof VerticalesBtpArtisansRoute
  '/verticales/e-commerce': typeof VerticalesECommerceRoute
  '/verticales/holdings-groupes': typeof VerticalesHoldingsGroupesRoute
  '/verticales/professions-liberales-sante': typeof VerticalesProfessionsLiberalesSanteRoute
  '/verticales/restauration-chr': typeof VerticalesRestaurationChrRoute
  '/verticales/sasu-tech': typeof VerticalesSasuTechRoute
  '/waitlist/success': typeof WaitlistSuccessRoute
  '/cabinet/cas-usage/cabinet-8-collaborateurs-departement': typeof CabinetCasUsageCabinet8CollaborateursDepartementRoute
  '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce': typeof CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute
  '/cabinet/cas-usage/cabinet-specialise-restauration': typeof CabinetCasUsageCabinetSpecialiseRestaurationRoute
  '/cabinet/cas-usage': typeof CabinetCasUsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/alternatives-primolead-experts-comptables': typeof AlternativesPrimoleadExpertsComptablesRoute
  '/canaux-activation': typeof CanauxActivationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/demo': typeof DemoRoute
  '/image-de-marque-expert-comptable': typeof ImageDeMarqueExpertComptableRoute
  '/inscription': typeof InscriptionRoute
  '/leads-experts-comptables': typeof LeadsExpertsComptablesRoute
  '/marque-et-visibilite-expert-comptable': typeof MarqueEtVisibiliteExpertComptableRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/newsletter': typeof NewsletterRoute
  '/newsletter-config': typeof NewsletterConfigRoute
  '/pourquoi-ce-lead-est-prioritaire': typeof PourquoiCeLeadEstPrioritaireRoute
  '/presence-digitale-cabinet-comptable': typeof PresenceDigitaleCabinetComptableRoute
  '/produit': typeof ProduitRoute
  '/prospection-cabinet-comptable': typeof ProspectionCabinetComptableRoute
  '/ressources': typeof RessourcesRoute
  '/sales-assistant': typeof SalesAssistantRoute
  '/simulateur-roi-ia-cabinet': typeof SimulateurRoiIaCabinetRoute
  '/solutions': typeof SolutionsRoute
  '/tarifs': typeof TarifsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/visibilite-expert-comptable': typeof VisibiliteExpertComptableRoute
  '/blog/5-leviers-croissance-cabinet-expertise-comptable': typeof Blog5LeviersCroissanceCabinetExpertiseComptableRoute
  '/blog/barometre-acquisition-cabinet-ec-2026': typeof BlogBarometreAcquisitionCabinetEc2026Route
  '/blog/barometre-immatriculations-juillet-2026': typeof BlogBarometreImmatriculationsJuillet2026Route
  '/blog/cas-client-empartners': typeof BlogCasClientEmpartnersRoute
  '/blog/cout-acquisition-client-cabinet-comptable': typeof BlogCoutAcquisitionClientCabinetComptableRoute
  '/blog/creations-entreprises-france-2025': typeof BlogCreationsEntreprisesFrance2025Route
  '/blog/creer-site-web-expert-comptable-guide': typeof BlogCreerSiteWebExpertComptableGuideRoute
  '/blog/fichier-siret-vs-plan-action-comptable': typeof BlogFichierSiretVsPlanActionComptableRoute
  '/blog/guide-demarchage-client-expert-comptable': typeof BlogGuideDemarchageClientExpertComptableRoute
  '/blog/icp-cabinet-expertise-comptable': typeof BlogIcpCabinetExpertiseComptableRoute
  '/blog/lexique-marketing-expert-comptable': typeof BlogLexiqueMarketingExpertComptableRoute
  '/blog/moderniser-cabinet-etat-lieux-2026': typeof BlogModerniserCabinetEtatLieux2026Route
  '/blog/moderniser-cabinet-expertise-comptable-ia': typeof BlogModerniserCabinetExpertiseComptableIaRoute
  '/blog/observatoire-sasu-sas-juin-2026': typeof BlogObservatoireSasuSasJuin2026Route
  '/blog/playbook-prospection-cabinet-ec-2026': typeof BlogPlaybookProspectionCabinetEc2026Route
  '/blog/referencement-local-expert-comptable': typeof BlogReferencementLocalExpertComptableRoute
  '/cabinet/glossaire': typeof CabinetGlossaireRoute
  '/verticales/btp-artisans': typeof VerticalesBtpArtisansRoute
  '/verticales/e-commerce': typeof VerticalesECommerceRoute
  '/verticales/holdings-groupes': typeof VerticalesHoldingsGroupesRoute
  '/verticales/professions-liberales-sante': typeof VerticalesProfessionsLiberalesSanteRoute
  '/verticales/restauration-chr': typeof VerticalesRestaurationChrRoute
  '/verticales/sasu-tech': typeof VerticalesSasuTechRoute
  '/waitlist/success': typeof WaitlistSuccessRoute
  '/cabinet/cas-usage/cabinet-8-collaborateurs-departement': typeof CabinetCasUsageCabinet8CollaborateursDepartementRoute
  '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce': typeof CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute
  '/cabinet/cas-usage/cabinet-specialise-restauration': typeof CabinetCasUsageCabinetSpecialiseRestaurationRoute
  '/cabinet/cas-usage/': typeof CabinetCasUsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/alternatives-primolead-experts-comptables'
    | '/canaux-activation'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/demo'
    | '/image-de-marque-expert-comptable'
    | '/inscription'
    | '/leads-experts-comptables'
    | '/marque-et-visibilite-expert-comptable'
    | '/mentions-legales'
    | '/newsletter'
    | '/newsletter-config'
    | '/pourquoi-ce-lead-est-prioritaire'
    | '/presence-digitale-cabinet-comptable'
    | '/produit'
    | '/prospection-cabinet-comptable'
    | '/ressources'
    | '/sales-assistant'
    | '/simulateur-roi-ia-cabinet'
    | '/solutions'
    | '/tarifs'
    | '/unsubscribe'
    | '/visibilite-expert-comptable'
    | '/blog/5-leviers-croissance-cabinet-expertise-comptable'
    | '/blog/barometre-acquisition-cabinet-ec-2026'
    | '/blog/barometre-immatriculations-juillet-2026'
    | '/blog/cas-client-empartners'
    | '/blog/cout-acquisition-client-cabinet-comptable'
    | '/blog/creations-entreprises-france-2025'
    | '/blog/creer-site-web-expert-comptable-guide'
    | '/blog/fichier-siret-vs-plan-action-comptable'
    | '/blog/guide-demarchage-client-expert-comptable'
    | '/blog/icp-cabinet-expertise-comptable'
    | '/blog/lexique-marketing-expert-comptable'
    | '/blog/moderniser-cabinet-etat-lieux-2026'
    | '/blog/moderniser-cabinet-expertise-comptable-ia'
    | '/blog/observatoire-sasu-sas-juin-2026'
    | '/blog/playbook-prospection-cabinet-ec-2026'
    | '/blog/referencement-local-expert-comptable'
    | '/cabinet/glossaire'
    | '/verticales/btp-artisans'
    | '/verticales/e-commerce'
    | '/verticales/holdings-groupes'
    | '/verticales/professions-liberales-sante'
    | '/verticales/restauration-chr'
    | '/verticales/sasu-tech'
    | '/waitlist/success'
    | '/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
    | '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
    | '/cabinet/cas-usage/cabinet-specialise-restauration'
    | '/cabinet/cas-usage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/alternatives-primolead-experts-comptables'
    | '/canaux-activation'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/demo'
    | '/image-de-marque-expert-comptable'
    | '/inscription'
    | '/leads-experts-comptables'
    | '/marque-et-visibilite-expert-comptable'
    | '/mentions-legales'
    | '/newsletter'
    | '/newsletter-config'
    | '/pourquoi-ce-lead-est-prioritaire'
    | '/presence-digitale-cabinet-comptable'
    | '/produit'
    | '/prospection-cabinet-comptable'
    | '/ressources'
    | '/sales-assistant'
    | '/simulateur-roi-ia-cabinet'
    | '/solutions'
    | '/tarifs'
    | '/unsubscribe'
    | '/visibilite-expert-comptable'
    | '/blog/5-leviers-croissance-cabinet-expertise-comptable'
    | '/blog/barometre-acquisition-cabinet-ec-2026'
    | '/blog/barometre-immatriculations-juillet-2026'
    | '/blog/cas-client-empartners'
    | '/blog/cout-acquisition-client-cabinet-comptable'
    | '/blog/creations-entreprises-france-2025'
    | '/blog/creer-site-web-expert-comptable-guide'
    | '/blog/fichier-siret-vs-plan-action-comptable'
    | '/blog/guide-demarchage-client-expert-comptable'
    | '/blog/icp-cabinet-expertise-comptable'
    | '/blog/lexique-marketing-expert-comptable'
    | '/blog/moderniser-cabinet-etat-lieux-2026'
    | '/blog/moderniser-cabinet-expertise-comptable-ia'
    | '/blog/observatoire-sasu-sas-juin-2026'
    | '/blog/playbook-prospection-cabinet-ec-2026'
    | '/blog/referencement-local-expert-comptable'
    | '/cabinet/glossaire'
    | '/verticales/btp-artisans'
    | '/verticales/e-commerce'
    | '/verticales/holdings-groupes'
    | '/verticales/professions-liberales-sante'
    | '/verticales/restauration-chr'
    | '/verticales/sasu-tech'
    | '/waitlist/success'
    | '/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
    | '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
    | '/cabinet/cas-usage/cabinet-specialise-restauration'
    | '/cabinet/cas-usage'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/alternatives-primolead-experts-comptables'
    | '/canaux-activation'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/demo'
    | '/image-de-marque-expert-comptable'
    | '/inscription'
    | '/leads-experts-comptables'
    | '/marque-et-visibilite-expert-comptable'
    | '/mentions-legales'
    | '/newsletter'
    | '/newsletter-config'
    | '/pourquoi-ce-lead-est-prioritaire'
    | '/presence-digitale-cabinet-comptable'
    | '/produit'
    | '/prospection-cabinet-comptable'
    | '/ressources'
    | '/sales-assistant'
    | '/simulateur-roi-ia-cabinet'
    | '/solutions'
    | '/tarifs'
    | '/unsubscribe'
    | '/visibilite-expert-comptable'
    | '/blog/5-leviers-croissance-cabinet-expertise-comptable'
    | '/blog/barometre-acquisition-cabinet-ec-2026'
    | '/blog/barometre-immatriculations-juillet-2026'
    | '/blog/cas-client-empartners'
    | '/blog/cout-acquisition-client-cabinet-comptable'
    | '/blog/creations-entreprises-france-2025'
    | '/blog/creer-site-web-expert-comptable-guide'
    | '/blog/fichier-siret-vs-plan-action-comptable'
    | '/blog/guide-demarchage-client-expert-comptable'
    | '/blog/icp-cabinet-expertise-comptable'
    | '/blog/lexique-marketing-expert-comptable'
    | '/blog/moderniser-cabinet-etat-lieux-2026'
    | '/blog/moderniser-cabinet-expertise-comptable-ia'
    | '/blog/observatoire-sasu-sas-juin-2026'
    | '/blog/playbook-prospection-cabinet-ec-2026'
    | '/blog/referencement-local-expert-comptable'
    | '/cabinet/glossaire'
    | '/verticales/btp-artisans'
    | '/verticales/e-commerce'
    | '/verticales/holdings-groupes'
    | '/verticales/professions-liberales-sante'
    | '/verticales/restauration-chr'
    | '/verticales/sasu-tech'
    | '/waitlist/success'
    | '/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
    | '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
    | '/cabinet/cas-usage/cabinet-specialise-restauration'
    | '/cabinet/cas-usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AlternativesPrimoleadExpertsComptablesRoute: typeof AlternativesPrimoleadExpertsComptablesRoute
  CanauxActivationRoute: typeof CanauxActivationRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  DemoRoute: typeof DemoRoute
  ImageDeMarqueExpertComptableRoute: typeof ImageDeMarqueExpertComptableRoute
  InscriptionRoute: typeof InscriptionRoute
  LeadsExpertsComptablesRoute: typeof LeadsExpertsComptablesRoute
  MarqueEtVisibiliteExpertComptableRoute: typeof MarqueEtVisibiliteExpertComptableRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NewsletterRoute: typeof NewsletterRoute
  NewsletterConfigRoute: typeof NewsletterConfigRoute
  PourquoiCeLeadEstPrioritaireRoute: typeof PourquoiCeLeadEstPrioritaireRoute
  PresenceDigitaleCabinetComptableRoute: typeof PresenceDigitaleCabinetComptableRoute
  ProduitRoute: typeof ProduitRoute
  ProspectionCabinetComptableRoute: typeof ProspectionCabinetComptableRoute
  RessourcesRoute: typeof RessourcesRoute
  SalesAssistantRoute: typeof SalesAssistantRoute
  SimulateurRoiIaCabinetRoute: typeof SimulateurRoiIaCabinetRoute
  SolutionsRoute: typeof SolutionsRoute
  TarifsRoute: typeof TarifsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VisibiliteExpertComptableRoute: typeof VisibiliteExpertComptableRoute
  Blog5LeviersCroissanceCabinetExpertiseComptableRoute: typeof Blog5LeviersCroissanceCabinetExpertiseComptableRoute
  BlogBarometreAcquisitionCabinetEc2026Route: typeof BlogBarometreAcquisitionCabinetEc2026Route
  BlogBarometreImmatriculationsJuillet2026Route: typeof BlogBarometreImmatriculationsJuillet2026Route
  BlogCasClientEmpartnersRoute: typeof BlogCasClientEmpartnersRoute
  BlogCoutAcquisitionClientCabinetComptableRoute: typeof BlogCoutAcquisitionClientCabinetComptableRoute
  BlogCreationsEntreprisesFrance2025Route: typeof BlogCreationsEntreprisesFrance2025Route
  BlogCreerSiteWebExpertComptableGuideRoute: typeof BlogCreerSiteWebExpertComptableGuideRoute
  BlogFichierSiretVsPlanActionComptableRoute: typeof BlogFichierSiretVsPlanActionComptableRoute
  BlogGuideDemarchageClientExpertComptableRoute: typeof BlogGuideDemarchageClientExpertComptableRoute
  BlogIcpCabinetExpertiseComptableRoute: typeof BlogIcpCabinetExpertiseComptableRoute
  BlogLexiqueMarketingExpertComptableRoute: typeof BlogLexiqueMarketingExpertComptableRoute
  BlogModerniserCabinetEtatLieux2026Route: typeof BlogModerniserCabinetEtatLieux2026Route
  BlogModerniserCabinetExpertiseComptableIaRoute: typeof BlogModerniserCabinetExpertiseComptableIaRoute
  BlogObservatoireSasuSasJuin2026Route: typeof BlogObservatoireSasuSasJuin2026Route
  BlogPlaybookProspectionCabinetEc2026Route: typeof BlogPlaybookProspectionCabinetEc2026Route
  BlogReferencementLocalExpertComptableRoute: typeof BlogReferencementLocalExpertComptableRoute
  CabinetGlossaireRoute: typeof CabinetGlossaireRoute
  VerticalesBtpArtisansRoute: typeof VerticalesBtpArtisansRoute
  VerticalesECommerceRoute: typeof VerticalesECommerceRoute
  VerticalesHoldingsGroupesRoute: typeof VerticalesHoldingsGroupesRoute
  VerticalesProfessionsLiberalesSanteRoute: typeof VerticalesProfessionsLiberalesSanteRoute
  VerticalesRestaurationChrRoute: typeof VerticalesRestaurationChrRoute
  VerticalesSasuTechRoute: typeof VerticalesSasuTechRoute
  WaitlistSuccessRoute: typeof WaitlistSuccessRoute
  CabinetCasUsageCabinet8CollaborateursDepartementRoute: typeof CabinetCasUsageCabinet8CollaborateursDepartementRoute
  CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute: typeof CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute
  CabinetCasUsageCabinetSpecialiseRestaurationRoute: typeof CabinetCasUsageCabinetSpecialiseRestaurationRoute
  CabinetCasUsageIndexRoute: typeof CabinetCasUsageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives-primolead-experts-comptables': {
      id: '/alternatives-primolead-experts-comptables'
      path: '/alternatives-primolead-experts-comptables'
      fullPath: '/alternatives-primolead-experts-comptables'
      preLoaderRoute: typeof AlternativesPrimoleadExpertsComptablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canaux-activation': {
      id: '/canaux-activation'
      path: '/canaux-activation'
      fullPath: '/canaux-activation'
      preLoaderRoute: typeof CanauxActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-de-marque-expert-comptable': {
      id: '/image-de-marque-expert-comptable'
      path: '/image-de-marque-expert-comptable'
      fullPath: '/image-de-marque-expert-comptable'
      preLoaderRoute: typeof ImageDeMarqueExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-experts-comptables': {
      id: '/leads-experts-comptables'
      path: '/leads-experts-comptables'
      fullPath: '/leads-experts-comptables'
      preLoaderRoute: typeof LeadsExpertsComptablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marque-et-visibilite-expert-comptable': {
      id: '/marque-et-visibilite-expert-comptable'
      path: '/marque-et-visibilite-expert-comptable'
      fullPath: '/marque-et-visibilite-expert-comptable'
      preLoaderRoute: typeof MarqueEtVisibiliteExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter-config': {
      id: '/newsletter-config'
      path: '/newsletter-config'
      fullPath: '/newsletter-config'
      preLoaderRoute: typeof NewsletterConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pourquoi-ce-lead-est-prioritaire': {
      id: '/pourquoi-ce-lead-est-prioritaire'
      path: '/pourquoi-ce-lead-est-prioritaire'
      fullPath: '/pourquoi-ce-lead-est-prioritaire'
      preLoaderRoute: typeof PourquoiCeLeadEstPrioritaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presence-digitale-cabinet-comptable': {
      id: '/presence-digitale-cabinet-comptable'
      path: '/presence-digitale-cabinet-comptable'
      fullPath: '/presence-digitale-cabinet-comptable'
      preLoaderRoute: typeof PresenceDigitaleCabinetComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit': {
      id: '/produit'
      path: '/produit'
      fullPath: '/produit'
      preLoaderRoute: typeof ProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection-cabinet-comptable': {
      id: '/prospection-cabinet-comptable'
      path: '/prospection-cabinet-comptable'
      fullPath: '/prospection-cabinet-comptable'
      preLoaderRoute: typeof ProspectionCabinetComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-assistant': {
      id: '/sales-assistant'
      path: '/sales-assistant'
      fullPath: '/sales-assistant'
      preLoaderRoute: typeof SalesAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur-roi-ia-cabinet': {
      id: '/simulateur-roi-ia-cabinet'
      path: '/simulateur-roi-ia-cabinet'
      fullPath: '/simulateur-roi-ia-cabinet'
      preLoaderRoute: typeof SimulateurRoiIaCabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visibilite-expert-comptable': {
      id: '/visibilite-expert-comptable'
      path: '/visibilite-expert-comptable'
      fullPath: '/visibilite-expert-comptable'
      preLoaderRoute: typeof VisibiliteExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/5-leviers-croissance-cabinet-expertise-comptable': {
      id: '/blog/5-leviers-croissance-cabinet-expertise-comptable'
      path: '/blog/5-leviers-croissance-cabinet-expertise-comptable'
      fullPath: '/blog/5-leviers-croissance-cabinet-expertise-comptable'
      preLoaderRoute: typeof Blog5LeviersCroissanceCabinetExpertiseComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/barometre-acquisition-cabinet-ec-2026': {
      id: '/blog/barometre-acquisition-cabinet-ec-2026'
      path: '/blog/barometre-acquisition-cabinet-ec-2026'
      fullPath: '/blog/barometre-acquisition-cabinet-ec-2026'
      preLoaderRoute: typeof BlogBarometreAcquisitionCabinetEc2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/barometre-immatriculations-juillet-2026': {
      id: '/blog/barometre-immatriculations-juillet-2026'
      path: '/blog/barometre-immatriculations-juillet-2026'
      fullPath: '/blog/barometre-immatriculations-juillet-2026'
      preLoaderRoute: typeof BlogBarometreImmatriculationsJuillet2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cas-client-empartners': {
      id: '/blog/cas-client-empartners'
      path: '/blog/cas-client-empartners'
      fullPath: '/blog/cas-client-empartners'
      preLoaderRoute: typeof BlogCasClientEmpartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cout-acquisition-client-cabinet-comptable': {
      id: '/blog/cout-acquisition-client-cabinet-comptable'
      path: '/blog/cout-acquisition-client-cabinet-comptable'
      fullPath: '/blog/cout-acquisition-client-cabinet-comptable'
      preLoaderRoute: typeof BlogCoutAcquisitionClientCabinetComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/creations-entreprises-france-2025': {
      id: '/blog/creations-entreprises-france-2025'
      path: '/blog/creations-entreprises-france-2025'
      fullPath: '/blog/creations-entreprises-france-2025'
      preLoaderRoute: typeof BlogCreationsEntreprisesFrance2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/creer-site-web-expert-comptable-guide': {
      id: '/blog/creer-site-web-expert-comptable-guide'
      path: '/blog/creer-site-web-expert-comptable-guide'
      fullPath: '/blog/creer-site-web-expert-comptable-guide'
      preLoaderRoute: typeof BlogCreerSiteWebExpertComptableGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/fichier-siret-vs-plan-action-comptable': {
      id: '/blog/fichier-siret-vs-plan-action-comptable'
      path: '/blog/fichier-siret-vs-plan-action-comptable'
      fullPath: '/blog/fichier-siret-vs-plan-action-comptable'
      preLoaderRoute: typeof BlogFichierSiretVsPlanActionComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/guide-demarchage-client-expert-comptable': {
      id: '/blog/guide-demarchage-client-expert-comptable'
      path: '/blog/guide-demarchage-client-expert-comptable'
      fullPath: '/blog/guide-demarchage-client-expert-comptable'
      preLoaderRoute: typeof BlogGuideDemarchageClientExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/icp-cabinet-expertise-comptable': {
      id: '/blog/icp-cabinet-expertise-comptable'
      path: '/blog/icp-cabinet-expertise-comptable'
      fullPath: '/blog/icp-cabinet-expertise-comptable'
      preLoaderRoute: typeof BlogIcpCabinetExpertiseComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/lexique-marketing-expert-comptable': {
      id: '/blog/lexique-marketing-expert-comptable'
      path: '/blog/lexique-marketing-expert-comptable'
      fullPath: '/blog/lexique-marketing-expert-comptable'
      preLoaderRoute: typeof BlogLexiqueMarketingExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/moderniser-cabinet-etat-lieux-2026': {
      id: '/blog/moderniser-cabinet-etat-lieux-2026'
      path: '/blog/moderniser-cabinet-etat-lieux-2026'
      fullPath: '/blog/moderniser-cabinet-etat-lieux-2026'
      preLoaderRoute: typeof BlogModerniserCabinetEtatLieux2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/moderniser-cabinet-expertise-comptable-ia': {
      id: '/blog/moderniser-cabinet-expertise-comptable-ia'
      path: '/blog/moderniser-cabinet-expertise-comptable-ia'
      fullPath: '/blog/moderniser-cabinet-expertise-comptable-ia'
      preLoaderRoute: typeof BlogModerniserCabinetExpertiseComptableIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/observatoire-sasu-sas-juin-2026': {
      id: '/blog/observatoire-sasu-sas-juin-2026'
      path: '/blog/observatoire-sasu-sas-juin-2026'
      fullPath: '/blog/observatoire-sasu-sas-juin-2026'
      preLoaderRoute: typeof BlogObservatoireSasuSasJuin2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/playbook-prospection-cabinet-ec-2026': {
      id: '/blog/playbook-prospection-cabinet-ec-2026'
      path: '/blog/playbook-prospection-cabinet-ec-2026'
      fullPath: '/blog/playbook-prospection-cabinet-ec-2026'
      preLoaderRoute: typeof BlogPlaybookProspectionCabinetEc2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/referencement-local-expert-comptable': {
      id: '/blog/referencement-local-expert-comptable'
      path: '/blog/referencement-local-expert-comptable'
      fullPath: '/blog/referencement-local-expert-comptable'
      preLoaderRoute: typeof BlogReferencementLocalExpertComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/glossaire': {
      id: '/cabinet/glossaire'
      path: '/cabinet/glossaire'
      fullPath: '/cabinet/glossaire'
      preLoaderRoute: typeof CabinetGlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticales/btp-artisans': {
      id: '/verticales/btp-artisans'
      path: '/verticales/btp-artisans'
      fullPath: '/verticales/btp-artisans'
      preLoaderRoute: typeof VerticalesBtpArtisansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticales/e-commerce': {
      id: '/verticales/e-commerce'
      path: '/verticales/e-commerce'
      fullPath: '/verticales/e-commerce'
      preLoaderRoute: typeof VerticalesECommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticales/holdings-groupes': {
      id: '/verticales/holdings-groupes'
      path: '/verticales/holdings-groupes'
      fullPath: '/verticales/holdings-groupes'
      preLoaderRoute: typeof VerticalesHoldingsGroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticales/professions-liberales-sante': {
      id: '/verticales/professions-liberales-sante'
      path: '/verticales/professions-liberales-sante'
      fullPath: '/verticales/professions-liberales-sante'
      preLoaderRoute: typeof VerticalesProfessionsLiberalesSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticales/restauration-chr': {
      id: '/verticales/restauration-chr'
      path: '/verticales/restauration-chr'
      fullPath: '/verticales/restauration-chr'
      preLoaderRoute: typeof VerticalesRestaurationChrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticales/sasu-tech': {
      id: '/verticales/sasu-tech'
      path: '/verticales/sasu-tech'
      fullPath: '/verticales/sasu-tech'
      preLoaderRoute: typeof VerticalesSasuTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/success': {
      id: '/waitlist/success'
      path: '/waitlist/success'
      fullPath: '/waitlist/success'
      preLoaderRoute: typeof WaitlistSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/cas-usage/': {
      id: '/cabinet/cas-usage/'
      path: '/cabinet/cas-usage'
      fullPath: '/cabinet/cas-usage/'
      preLoaderRoute: typeof CabinetCasUsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/cas-usage/cabinet-8-collaborateurs-departement': {
      id: '/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
      path: '/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
      fullPath: '/cabinet/cas-usage/cabinet-8-collaborateurs-departement'
      preLoaderRoute: typeof CabinetCasUsageCabinet8CollaborateursDepartementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce': {
      id: '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
      path: '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
      fullPath: '/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce'
      preLoaderRoute: typeof CabinetCasUsageCabinetFullRemoteStartupsEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/cas-usage/cabinet-specialise-restauration': {
      id: '/cabinet/cas-usage/cabinet-specialise-restauration'
      path: '/cabinet/cas-usage/cabinet-specialise-restauration'
      fullPath: '/cabinet/cas-usage/cabinet-specialise-restauration'
      preLoaderRoute: typeof CabinetCasUsageCabinetSpecialiseRestaurationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AlternativesPrimoleadExpertsComptablesRoute:
    AlternativesPrimoleadExpertsComptablesRoute,
  CanauxActivationRoute: CanauxActivationRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  DemoRoute: DemoRoute,
  ImageDeMarqueExpertComptableRoute: ImageDeMarqueExpertComptableRoute,
  InscriptionRoute: InscriptionRoute,
  LeadsExpertsComptablesRoute: LeadsExpertsComptablesRoute,
  MarqueEtVisibiliteExpertComptableRoute:
    MarqueEtVisibiliteExpertComptableRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NewsletterRoute: NewsletterRoute,
  NewsletterConfigRoute: NewsletterConfigRoute,
  PourquoiCeLeadEstPrioritaireRoute: PourquoiCeLeadEstPrioritaireRoute,
  PresenceDigitaleCabinetComptableRoute: PresenceDigitaleCabinetComptableRoute,
  ProduitRoute: ProduitRoute,
  ProspectionCabinetComptableRoute: ProspectionCabinetComptableRoute,
  RessourcesRoute: RessourcesRoute,
  SalesAssistantRoute: SalesAssistantRoute,
  SimulateurRoiIaCabinetRoute: SimulateurRoiIaCabinetRoute,
  SolutionsRoute: SolutionsRoute,
  TarifsRoute: TarifsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VisibiliteExpertComptableRoute: VisibiliteExpertComptableRoute,
  Blog5LeviersCroissanceCabinetExpertiseComptableRoute:
    Blog5LeviersCroissanceCabinetExpertiseComptableRoute,
  BlogBarometreAcquisitionCabinetEc2026Route:
    BlogBarometreAcquisitionCabinetEc2026Route,
  BlogBarometreImmatriculationsJuillet2026Route:
    BlogBarometreImmatriculationsJuillet2026Route,
  BlogCasClientEmpartnersRoute: BlogCasClientEmpartnersRoute,
  BlogCoutAcquisitionClientCabinetComptableRoute:
    BlogCoutAcquisitionClientCabinetComptableRoute,
  BlogCreationsEntreprisesFrance2025Route:
    BlogCreationsEntreprisesFrance2025Route,
  BlogCreerSiteWebExpertComptableGuideRoute:
    BlogCreerSiteWebExpertComptableGuideRoute,
  BlogFichierSiretVsPlanActionComptableRoute:
    BlogFichierSiretVsPlanActionComptableRoute,
  BlogGuideDemarchageClientExpertComptableRoute:
    BlogGuideDemarchageClientExpertComptableRoute,
  BlogIcpCabinetExpertiseComptableRoute: BlogIcpCabinetExpertiseComptableRoute,
  BlogLexiqueMarketingExpertComptableRoute:
    BlogLexiqueMarketingExpertComptableRoute,
  BlogModerniserCabinetEtatLieux2026Route:
    BlogModerniserCabinetEtatLieux2026Route,
  BlogModerniserCabinetExpertiseComptableIaRoute:
    BlogModerniserCabinetExpertiseComptableIaRoute,
  BlogObservatoireSasuSasJuin2026Route: BlogObservatoireSasuSasJuin2026Route,
  BlogPlaybookProspectionCabinetEc2026Route:
    BlogPlaybookProspectionCabinetEc2026Route,
  BlogReferencementLocalExpertComptableRoute:
    BlogReferencementLocalExpertComptableRoute,
  CabinetGlossaireRoute: CabinetGlossaireRoute,
  VerticalesBtpArtisansRoute: VerticalesBtpArtisansRoute,
  VerticalesECommerceRoute: VerticalesECommerceRoute,
  VerticalesHoldingsGroupesRoute: VerticalesHoldingsGroupesRoute,
  VerticalesProfessionsLiberalesSanteRoute:
    VerticalesProfessionsLiberalesSanteRoute,
  VerticalesRestaurationChrRoute: VerticalesRestaurationChrRoute,
  VerticalesSasuTechRoute: VerticalesSasuTechRoute,
  WaitlistSuccessRoute: WaitlistSuccessRoute,
  CabinetCasUsageCabinet8CollaborateursDepartementRoute:
    CabinetCasUsageCabinet8CollaborateursDepartementRoute,
  CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute:
    CabinetCasUsageCabinetFullRemoteStartupsEcommerceRoute,
  CabinetCasUsageCabinetSpecialiseRestaurationRoute:
    CabinetCasUsageCabinetSpecialiseRestaurationRoute,
  CabinetCasUsageIndexRoute: CabinetCasUsageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
