// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-blog-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
import { ROUTE_META } from "npm:@/lib/route-meta";
var ARTICLES = Object.entries(ROUTE_META).filter(([path]) => path.startsWith("/blog/")).map(([path, meta]) => ({
  slug: path.replace("/blog/", ""),
  title: meta.title,
  description: meta.description,
  url: `https://eligibly.ai${path}`
})).sort((a, b) => a.slug.localeCompare(b.slug));
var list_blog_articles_default = defineTool({
  name: "list_blog_articles",
  title: "List blog articles",
  description: "List Eligibly's published blog articles (title, slug, description, url) about acquisition, prospection and marketing for accounting firms.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to filter titles/slugs.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const q = search?.trim().toLowerCase();
    const items = q ? ARTICLES.filter((a) => a.title.toLowerCase().includes(q) || a.slug.includes(q)) : ARTICLES;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { articles: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get Eligibly pricing",
  description: "Return Eligibly's current public pricing for accounting firms (per-lead model + free pilot).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const pricing = {
      plan: "Eligibly Cabinet",
      price_model: "per_qualified_lead",
      starting_price_eur_ht_per_lead: 10,
      billing: "monthly based on delivered leads",
      pilot: { free: true, duration_days: 14, credit_card_required: false },
      commitment: "Sans engagement",
      url: "https://eligibly.ai/tarifs"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
      structuredContent: pricing
    };
  }
});

// src/lib/mcp/tools/submit-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var submit_lead_default = defineTool3({
  name: "submit_lead",
  title: "Submit a demo/pilot lead",
  description: "Submit a lead requesting a demo or the free 14-day pilot of Eligibly. Sends the request to the Eligibly team.",
  inputSchema: {
    full_name: z2.string().min(2).describe("Contact full name."),
    email: z2.string().email().describe("Professional email address."),
    firm_name: z2.string().min(1).describe("Accounting firm name."),
    phone: z2.string().optional().describe("Optional phone number."),
    message: z2.string().optional().describe("Optional context or question.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ full_name, email, firm_name, phone, message }) => {
    const supabaseUrl = process.env["SUPABASE_URL"];
    if (!supabaseUrl) {
      return { content: [{ type: "text", text: "Server not configured (SUPABASE_URL missing)." }], isError: true };
    }
    try {
      const res = await fetch(`${supabaseUrl}/functions/v1/submit-lead`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ full_name, email, firm_name, phone, message, source: "mcp" })
      });
      const text = await res.text();
      if (!res.ok) {
        return { content: [{ type: "text", text: `Lead submission failed (${res.status}): ${text}` }], isError: true };
      }
      return {
        content: [{ type: "text", text: "Lead submitted. Eligibly's team will get in touch shortly." }],
        structuredContent: { ok: true }
      };
    } catch (err) {
      return { content: [{ type: "text", text: `Lead submission error: ${err.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "eligibly-mcp",
  title: "Eligibly MCP",
  version: "0.1.0",
  instructions: "Tools for Eligibly, the prospecting CRM for French accounting firms targeting freshly registered SASU/SAS/EURL/SARL/SEL. Use `get_pricing` for current pricing, `list_blog_articles` to surface Eligibly's published resources, and `submit_lead` to book a demo or the free 14-day pilot.",
  // @ts-expect-error upstream @lovable.dev/mcp-js type bug: AnyToolDefinition.outputSchema is incompatible with exactOptionalPropertyTypes
  tools: [list_blog_articles_default, get_pricing_default, submit_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
