// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-blog-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/route-meta.ts
var ROUTE_META = {
  "/": { title: "Eligibly \u2014 D\xE9tectez. Scorez. Signez. Vos futurs clients en 90 j.", description: "D\xE9tectez chaque SASU/SAS/EURL/SARL/SEL immatricul\xE9e en France, scorez-la sur votre ICP, contactez-la dans la fen\xEAtre \u2264 90 jours. Digest livr\xE9 \xE0 7h chaque matin. Pilote 14 j gratuit, sans CB." },
  "/a-propos": { title: "\xC0 propos d'Eligibly \u2014 D\xE9tectez, scorez et signez vos futurs clients", description: "Notre mission : que chaque cabinet EC produise ses propres leads, jamais mutualis\xE9s. \xC9quipe, vision, valeurs et engagement de moyens." },
  "/alternatives-primolead-experts-comptables": { title: "Alternatives \xE0 PrimoLead pour cabinets d'expertise comptable", description: "Comparatif neutre : PrimoLead, Corporama, Societe.com, Eligibly. Sources, filtres, scoring, canaux d'activation, prix, essai. Choisir le bon outil de g\xE9n\xE9ration de leads pour son cabinet EC." },
  "/blog/5-leviers-croissance-cabinet-expertise-comptable": { title: "La croissance d'un cabinet ne se prie pas. Elle se provoque.", description: "5 leviers concrets pour d\xE9velopper un cabinet d'expertise comptable en 2026 : entretenir son r\xE9seau prescripteur, se sp\xE9cialiser, automatiser la production, occuper LinkedIn, jouer le timing de cr\xE9ation." },
  "/blog/barometre-acquisition-cabinet-ec-2026": { title: "Barom\xE8tre 2026 \u2014 L'acquisition client en cabinet d'expertise comptable", description: "Barom\xE8tre 2026 de l'acquisition client en cabinet EC : CAC, CPL, mix de canaux, cycle de vente, conversion. Lecture strat\xE9gique pour le r\xF4le de conseil de l'expert-comptable." },
  "/blog/barometre-immatriculations-juillet-2026": { title: "Barom\xE8tre des nouvelles soci\xE9t\xE9s commerciales \u2014 \xC9dition juillet 2026", description: "Barom\xE8tre juillet 2026 : 718 immatriculations analys\xE9es, +11,8% vs juin, concentration Tech/Conseil/E-commerce/CHR, capital m\xE9dian 1 000 \u20AC. Signaux structur\xE9s pour les cabinets EC." },
  "/blog/cas-client-empartners": { title: "Cas client Empartners : 3 leads qualifi\xE9s par semaine, d\xE8s 3 mois, sur un site g\xE9n\xE9rant quelques centaines de visites", description: "Cas client Empartners.fr : cabinet d'expertise comptable accompagn\xE9 par Eligibly sur l'image de marque, le site web, le r\xE9f\xE9rencement local et la g\xE9n\xE9ration de leads. R\xE9sultat : 3 leads qualifi\xE9s par semaine d\xE8s 3 mois, depuis f\xE9vrier 2026." },
  "/blog/cout-acquisition-client-cabinet-comptable": { title: "Combien co\xFBte un nouveau client en cabinet d'expertise comptable ? Benchmark 2026", description: "Benchmarks 2026 du co\xFBt d'acquisition client en B2B et lecture sp\xE9cifique pour les cabinets d'expertise comptable : achat de leads, Google Ads, cold email, prospection sortante, apport." },
  "/blog/creations-entreprises-france-2025": { title: "Cr\xE9ations d'entreprises en France : 2025, l'ann\xE9e record qui change la donne pour les cabinets EC", description: "Analyse des donn\xE9es INSEE sur les cr\xE9ations d'entreprises 2024-2025 en France : volume, formes juridiques (SASU, SAS, SARL), r\xE9gions, et opportunit\xE9s concr\xE8tes pour les cabinets d'expertise comptable." },
  "/blog/creer-site-web-expert-comptable-guide": { title: "Cr\xE9er le site web d'un cabinet d'expertise comptable : guide de conception 2026", description: "Guide de conception d'un site web pour cabinet d'expertise comptable : positionnement et ICP, arborescence type (accueil, pages missions, verticales, \xE9quipe, contact, blog), tunnel de conversion, socle technique et Core Web Vitals, conformit\xE9 d\xE9ontologique et RGPD, budget et d\xE9lais r\xE9alistes, indicateurs \xE0 suivre." },
  "/blog/fichier-siret-vs-plan-action-comptable": { title: "Fichier de SIRET vs plan d'action : ce qui change vraiment pour un cabinet EC", description: "Comparatif approfondi entre les fichiers de SIRET pour cabinets d'expertise comptable et une plateforme qui livre scoring, canal recommand\xE9 et accroche pr\xEAte \xE0 envoyer." },
  "/blog/guide-demarchage-client-expert-comptable": { title: "Kit marketing 2026 pour experts-comptables : sortir de la posture d'attente", description: "Kit marketing 2026 pour experts-comptables : cadre d\xE9ontologique post-2014, pr\xE9sence sociale, canaux fluides (Slack, WhatsApp), d\xE9marchage direct, timing d'immatriculation et checklist marketing en 12 axes (site web qui convertit, Google avis, SEO, visibilit\xE9 LLM, r\xE9seaux sociaux, formulaires de contact, outbound Eligibly, canal prescripteur, lead magnets, webinaires, t\xE9moignages et parrainage). Sources CNOEC, INSEE, L\xE9gifrance. Cas Empartners : 3 leads / semaine en 3 mois." },
  "/blog/icp-cabinet-expertise-comptable": { title: "Construire l'ICP d'un cabinet d'expertise comptable : la m\xE9thode en 5 \xE9tapes", description: "M\xE9thode pas-\xE0-pas pour d\xE9finir l'Ideal Customer Profile d'un cabinet d'expertise comptable : crit\xE8res durs, signaux, verticales sous-exploit\xE9es, exclusions, et conversion en filtres op\xE9rationnels." },
  "/blog/lexique-marketing-expert-comptable": { title: "Lexique marketing pour experts-comptables \u2014 30 mots \xE0 conna\xEEtre", description: "Glossaire des 30 termes marketing essentiels pour piloter la prospection en cabinet d'expertise comptable : ICP, scoring, pipeline, touchpoints, CAC, MQL, outbound, s\xE9quence, signal d'achat, ROI commercial." },
  "/blog/moderniser-cabinet-etat-lieux-2026": { title: "Moderniser son cabinet : l'\xE9tat des lieux 2026", description: "\xC9tat des lieux 2026 de la profession comptable : 20 Md\u20AC de CA, 21 288 cabinets, 77% des entreprises accompagn\xE9es, 232 000 futurs clients / an. Les chiffres, tous sourc\xE9s." },
  "/blog/moderniser-cabinet-expertise-comptable-ia": { title: "Moderniser un cabinet d'expertise comptable \xE0 l'\xE8re de l'IA : les 6 axes qui comptent en 2026", description: "Les 6 axes de modernisation IA d'un cabinet d'expertise comptable en 2026 : production, conseil, relation client, RH, gouvernance et d\xE9veloppement commercial. Sources OEC, Cegid, Shine, CREOP." },
  "/blog/observatoire-sasu-sas-juin-2026": { title: "Observatoire des SASU & SAS cr\xE9\xE9es en France \u2014 \xC9dition juin 2026", description: "Observatoire mensuel des SASU et SAS immatricul\xE9es en France. Lecture strat\xE9gique pour les cabinets d'expertise comptable : volumes, verticales, g\xE9ographie, profils." },
  "/blog/playbook-prospection-cabinet-ec-2026": { title: "Le Playbook 2026 de la prospection en cabinet d'expertise comptable", description: "Playbook complet pour structurer la prospection d'un cabinet d'expertise comptable en 2026 : ICP, organisation, s\xE9quences, posture conseil, IA, gouvernance." },
  "/blog/referencement-local-expert-comptable": { title: "R\xE9f\xE9rencement local d'un expert-comptable : la m\xE9thode compl\xE8te 2026", description: "M\xE9thode de r\xE9f\xE9rencement local pour cabinet d'expertise comptable : optimisation de la fiche Google Business Profile, collecte d'avis, coh\xE9rence NAP, pages locales et verticales, netlinking de proximit\xE9, visibilit\xE9 dans ChatGPT et Perplexity. Plan d'action 90 jours et KPIs." },
  "/cabinet/cas-usage": { title: "Cas d'usage \u2014 Eligibly pour cabinets d'expertise comptable", description: "Trois cas d'usage d\xE9taill\xE9s : cabinet g\xE9n\xE9raliste 8 collaborateurs, cabinet sp\xE9cialis\xE9 restauration, cabinet full-remote startups/e-commerce. Configuration, signaux, plan d'action." },
  "/cabinet/cas-usage/cabinet-8-collaborateurs-departement": { title: "Cabinet 8 collaborateurs : 30 leads/semaine dans son d\xE9partement", description: "Cas d'usage cabinet EC g\xE9n\xE9raliste de 8 collaborateurs : configuration ICP, filtres INPI/BODACC, plan d'action semaine type. 30 prospects qualifi\xE9s / semaine sur un d\xE9partement." },
  "/cabinet/cas-usage/cabinet-full-remote-startups-ecommerce": { title: "Cabinet full-remote : cibler startups & e-commer\xE7ants \u2014 cas d'usage", description: "Cabinet 100 % remote : ciblage national SASU tech + e-commerce, canal LinkedIn + email prioritaire, plan d'action semaine type." },
  "/cabinet/cas-usage/cabinet-specialise-restauration": { title: "Cabinet EC sp\xE9cialis\xE9 restauration : d\xE9tecter les nouvelles SAS/SARL", description: "Cas d'usage cabinet vertical restauration : filtres NAF 56xx, capital, licence III/IV, plan d'action paie + juridique. Prospection cibl\xE9e haut de gamme." },
  "/cabinet/glossaire": { title: "Glossaire \u2014 Prospection & g\xE9n\xE9ration de leads cabinet d'expertise comptable", description: "D\xE9finitions courtes et pr\xE9cises : SIRENE, INPI, BODACC, ICP, scoring pr\xE9dictif, CAC, LTV, code APE 6920Z, SASU, SAS, EURL, canal d'activation. Glossaire pour cabinets EC." },
  "/canaux-activation": { title: "Canaux d'activation cabinet : WhatsApp Business, LinkedIn, email, appel, courrier", description: "Pour chaque lead cabinet, le meilleur canal : WhatsApp Business, LinkedIn, email, appel, Instagram DM ou courrier en-t\xEAte. Timing, m\xE9thode, taux de conversion observ\xE9s." },
  "/cgu": { title: "Conditions g\xE9n\xE9rales d'utilisation \u2014 Eligibly", description: "Conditions g\xE9n\xE9rales d'utilisation d'Eligibly : acc\xE8s au service, obligations utilisateurs, propri\xE9t\xE9 intellectuelle, responsabilit\xE9s et r\xE9siliation." },
  "/confidentialite": { title: "Politique de confidentialit\xE9 \u2014 Eligibly", description: "Politique de confidentialit\xE9 et RGPD d'Eligibly : donn\xE9es collect\xE9es, finalit\xE9s, dur\xE9es de conservation, droits d'acc\xE8s et de suppression." },
  "/connexion": { title: "Connexion \u2014 Eligibly", description: "Connectez-vous \xE0 votre espace Eligibly pour acc\xE9der \xE0 vos leads scor\xE9s et votre plan d'action quotidien." },
  "/demo": { title: "D\xE9mo Eligibly \u2014 10 leads scor\xE9s sur votre zone, en 20 min", description: "R\xE9servez une d\xE9mo 20 min : 10 SASU/SAS/EURL/SARL/SEL scor\xE9es sur votre zone, canal d'approche recommand\xE9, accroche pr\xEAte \xE0 envoyer. Sans CB, sans engagement." },
  "/image-de-marque-expert-comptable": { title: "Image de marque expert-comptable : positionnement et preuves", description: "Construire l'image de marque d'un cabinet d'expertise comptable : positionnement, verticalisation, preuves, identit\xE9, discours associ\xE9s. Cadre op\xE9rationnel et limites d\xE9ontologiques." },
  "/inscription": { title: "Inscription \u2014 Eligibly", description: "Cr\xE9ez votre compte Eligibly et d\xE9marrez votre pilote de 14 jours gratuit, sans carte bancaire." },
  "/leads-experts-comptables": { title: "G\xE9n\xE9ration de leads pour experts-comptables \u2014 Eligibly", description: "Logiciel de g\xE9n\xE9ration de leads vertical pour cabinets d'expertise comptable. D\xE9tection SASU/SAS/EURL/SARL/SEL immatricul\xE9es, scoring expliqu\xE9, canaux d'activation. Sources INPI \xB7 Sirene \xB7 BODACC. Pilote 14 j sans CB." },
  "/marque-et-visibilite-expert-comptable": { title: "Marque & visibilit\xE9 expert-comptable \u2014 l'offre Eligibly (2026)", description: "Offre marque & visibilit\xE9 pour cabinet d'expertise comptable : actifs digitaux, cas clients document\xE9s, calculateur d'impact visibilit\xE9 et tableaux de bord de maturit\xE9." },
  "/mentions-legales": { title: "Mentions l\xE9gales \u2014 Eligibly", description: "Mentions l\xE9gales d'Eligibly : \xE9diteur GM2.0 SAS, RCS Paris 930 166 913, si\xE8ge 9 Avenue de Bouvines 75011 Paris, h\xE9bergement et contact." },
  "/newsletter": { title: "Newsletter Eligibly \u2014 Le digest prospection des cabinets EC", description: "Recevez chaque mois les chiffres d'immatriculation, benchmarks CAC et m\xE9thodes de prospection pour cabinets d'expertise comptable." },
  "/newsletter-config": { title: "Configuration newsletter \u2014 Eligibly", description: "G\xE9rez vos pr\xE9f\xE9rences d'abonnement \xE0 la newsletter Eligibly." },
  "/pourquoi-ce-lead-est-prioritaire": { title: "Fiche lead cabinet EC : score 84/100 expliqu\xE9 (exemple)", description: "Exemple concret : SASU conseil IT \xE0 Paris, capital 5 000 \u20AC, score 84/100. Signaux positifs, points \xE0 v\xE9rifier, canal recommand\xE9, accroche pr\xEAte \xE0 envoyer." },
  "/presence-digitale-cabinet-comptable": { title: "Pr\xE9sence digitale cabinet comptable : socle technique et cadence", description: "Checklist de pr\xE9sence digitale pour cabinet d'expertise comptable : site, fiche Google, LinkedIn, annuaires m\xE9tier, avis, contenu. Priorit\xE9s, co\xFBts et cadence r\xE9aliste." },
  "/produit": { title: "D\xE9tection & prospection \u2014 L'offre Eligibly pour cabinets EC", description: "D\xE9tection quotidienne des nouvelles SASU/SAS/EURL/SARL/SEL, filtres ICP, scoring expliqu\xE9 et canal d'approche recommand\xE9 (LinkedIn, email, appel, WhatsApp, courrier). Sales Assistant inclus. RGPD." },
  "/prospection-cabinet-comptable": { title: "Prospection cabinet comptable \u2014 La m\xE9thode 2026 (guide complet)", description: "Structurer une prospection rentable pour cabinet EC en 2026 : sourcing, scoring, s\xE9quences multicanal, gouvernance, KPIs. Guide op\xE9rationnel + mod\xE8les." },
  "/ressources": { title: "Ressources cabinet EC \u2014 Barom\xE8tres, playbooks & analyses sourc\xE9es", description: "Barom\xE8tres CAC, playbooks de prospection, ICP, s\xE9quences multicanal, observatoires SASU/SAS : les analyses sourc\xE9es (INSEE, OEC, Atlas) pour votre cabinet." },
  "/sales-assistant": { title: "Sales Assistant Eligibly \u2014 Copilote IA de prospection pour cabinets EC", description: "4 canaux (LinkedIn \xB7 Email \xB7 T\xE9l\xE9phone \xB7 Courrier), 9 besoins d\xE9tect\xE9s par lead, plan d'action pr\xEAt \xE0 envoyer. \xC0 partir de 10 \u20AC HT/lead, pilote 14 jours sans CB." },
  "/simulateur-roi-ia-cabinet": { title: "Simulateur ROI IA cabinet comptable \u2014 Gains chiffr\xE9s en 4 \xE9tapes", description: "Calculez les gains nets de l'IA pour votre cabinet d'expertise comptable : production, conseil, prospection. Simulateur gratuit en 4 \xE9tapes, r\xE9sultats imm\xE9diats." },
  "/solutions": { title: "Cas d'usage cabinet EC \u2014 6 profils, filtres & b\xE9n\xE9fices concrets", description: "6 verticales cabinet EC : Tech, Conseil, Sant\xE9, Artisans, Grands cabinets, Structuration commerciale. Filtres appliqu\xE9s et gains chiffr\xE9s par profil." },
  "/tarifs": { title: "Tarifs Eligibly \u2014 \xC0 partir de 10 \u20AC le lead qualifi\xE9, devis sur mesure", description: "\xC0 partir de 10 \u20AC le lead qualifi\xE9, ajust\xE9 \xE0 votre volume et \xE0 la taille de votre cabinet EC. Pilote 14 jours sans carte bancaire. R\xE9siliation mensuelle." },
  "/verticales/btp-artisans": { title: "Verticale BTP & Artisans \u2014 Eligibly pour cabinets EC du b\xE2timent", description: "D\xE9tectez chaque nouvelle SASU/SAS/EURL/SARL/SEL BTP (NAF 41-43). Signaux : capital, qualification RGE, sous-traitance. Besoins autoliquidation TVA, garantie d\xE9cennale, paie." },
  "/verticales/e-commerce": { title: "Verticale E-commerce \u2014 Eligibly pour cabinets EC sp\xE9cialis\xE9s DNVB & marketplaces", description: "Ciblez les nouvelles SASU/SAS/EURL/SARL/SEL e-commerce (NAF 47.91B, 47.19B). Signaux : Shopify, WooCommerce, dropshipping. Besoins TVA UE, OSS/IOSS, marketplaces." },
  "/verticales/holdings-groupes": { title: "Verticale Holdings & Groupes \u2014 Eligibly pour cabinets EC haut de gamme", description: "Ciblez les nouvelles holdings, SPFPL, soci\xE9t\xE9s civiles patrimoniales. Signaux : capital \xE9lev\xE9, multi-associ\xE9s, montage LBO. ARPU 8-25 k\u20AC/an." },
  "/verticales/professions-liberales-sante": { title: "Verticale Professions lib\xE9rales & Sant\xE9 \u2014 Eligibly pour cabinets EC BNC/SEL", description: "Ciblez les nouvelles SELAS, SELARL, SASU BNC (m\xE9decins, kin\xE9s, avocats, architectes). Besoins arbitrage BNC vs SEL, CARPIMKO, retraite lib\xE9rale." },
  "/verticales/restauration-chr": { title: "Verticale Restauration & CHR \u2014 Eligibly pour cabinets sp\xE9cialis\xE9s paie multi-\xE9tablissements", description: "D\xE9tectez chaque nouvelle SAS/SARL restauration (NAF 56xx). Signaux licence III/IV, capital, multi-\xE9tablissements. Besoins paie, TVA, juridique." },
  "/verticales/sasu-tech": { title: "Verticale SASU Tech & Conseil IT \u2014 Eligibly pour cabinets EC", description: "Configuration Eligibly pour cibler les nouvelles SASU tech, freelances IT et micro-ESN. Filtres NAF 62/63, capital, dirigeant ex-ESN. Digest matinal + plan d'action LinkedIn/email." },
  "/visibilite-expert-comptable": { title: "Visibilit\xE9 expert-comptable : \xEAtre trouv\xE9, choisi et cit\xE9 (2026)", description: "M\xE9thode de visibilit\xE9 pour cabinet d'expertise comptable : fiche Google Business, r\xE9f\xE9rencement local, contenu, pr\xE9sence dans les LLM. Indicateurs et arbitrages de budget." },
  "/waitlist/success": { title: "Inscription confirm\xE9e \u2014 Eligibly", description: "Votre inscription \xE0 la liste d'attente Eligibly est confirm\xE9e. Nous revenons vers vous rapidement." }
};
var DEFAULT_META = ROUTE_META["/"];

// src/lib/mcp/tools/list-blog-articles.ts
var ARTICLES = Object.entries(ROUTE_META).filter(([path]) => path.startsWith("/blog/")).map(([path, meta]) => ({
  slug: path.replace("/blog/", ""),
  title: meta.title,
  description: meta.description,
  url: `https://eligibly.ai${path}`
})).sort((a, b) => a.slug.localeCompare(b.slug));
var list_blog_articles_default = defineTool({
  name: "list_blog_articles",
  title: "List blog articles",
  description: "List Eligibly's published blog articles (title, slug, description, url) about acquisition, prospection and marketing for accounting firms.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to filter titles/slugs.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const q = search?.trim().toLowerCase();
    const items = q ? ARTICLES.filter((a) => a.title.toLowerCase().includes(q) || a.slug.includes(q)) : ARTICLES;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { articles: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get Eligibly pricing",
  description: "Return Eligibly's current public pricing for accounting firms (per-lead model + free pilot).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const pricing = {
      plan: "Eligibly Cabinet",
      price_model: "per_qualified_lead",
      starting_price_eur_ht_per_lead: 10,
      billing: "monthly based on delivered leads",
      pilot: { free: true, duration_days: 14, credit_card_required: false },
      commitment: "Sans engagement",
      url: "https://eligibly.ai/tarifs"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
      structuredContent: pricing
    };
  }
});

// src/lib/mcp/tools/submit-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var submit_lead_default = defineTool3({
  name: "submit_lead",
  title: "Submit a demo/pilot lead",
  description: "Submit a lead requesting a demo or the free 14-day pilot of Eligibly. Sends the request to the Eligibly team.",
  inputSchema: {
    full_name: z2.string().min(2).describe("Contact full name."),
    email: z2.string().email().describe("Professional email address."),
    firm_name: z2.string().min(1).describe("Accounting firm name."),
    phone: z2.string().optional().describe("Optional phone number."),
    message: z2.string().optional().describe("Optional context or question.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ full_name, email, firm_name, phone, message }) => {
    const supabaseUrl = process.env["SUPABASE_URL"];
    if (!supabaseUrl) {
      return { content: [{ type: "text", text: "Server not configured (SUPABASE_URL missing)." }], isError: true };
    }
    try {
      const res = await fetch(`${supabaseUrl}/functions/v1/submit-lead`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ full_name, email, firm_name, phone, message, source: "mcp" })
      });
      const text = await res.text();
      if (!res.ok) {
        return { content: [{ type: "text", text: `Lead submission failed (${res.status}): ${text}` }], isError: true };
      }
      return {
        content: [{ type: "text", text: "Lead submitted. Eligibly's team will get in touch shortly." }],
        structuredContent: { ok: true }
      };
    } catch (err) {
      return { content: [{ type: "text", text: `Lead submission error: ${err.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "eligibly-mcp",
  title: "Eligibly MCP",
  version: "0.1.0",
  instructions: "Tools for Eligibly, the prospecting CRM for French accounting firms targeting freshly registered SASU/SAS/EURL/SARL/SEL. Use `get_pricing` for current pricing, `list_blog_articles` to surface Eligibly's published resources, and `submit_lead` to book a demo or the free 14-day pilot.",
  // @ts-expect-error upstream @lovable.dev/mcp-js type bug: AnyToolDefinition.outputSchema is incompatible with exactOptionalPropertyTypes
  tools: [list_blog_articles_default, get_pricing_default, submit_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
